WEBUI-28: refresh clipboard based on content update.
nuxeo/nuxeo-web-ui pull request #1010
Opened 2020-09-03 14:50 UTC by richardsd

Ok, I'm opening the PR for further discussion on the topic.
- `nuxeo-clipboard` is using the `nuxeo-document-storage` to store the documents in the clipboard. 
- `nuxeo-document-storage` is [updating](https://github.com/nuxeo/nuxeo-web-ui/blob/master/elements/nuxeo-document-storage/nuxeo-document-storage.js#L85) the `documents` array and [notifying](https://github.com/nuxeo/nuxeo-web-ui/blob/master/elements/nuxeo-document-storage/nuxeo-document-storage.js#L95) the `nuxeo-clipboard`
- However, `nuxeo-clipboard` is not listening to array splices or any update inside the `documents` property (`!canPaste(documents, targetDocument)` only listens to changes in the `documents` itself).

What do you think would be a good approach to handle this? 
I thought about listening to splices (`documents.splices`) or even all updates (`documents.*`), but I am wondering what you usually do in similar cases.

2020-09-03 14:50 UTC, nuxeojenkins commented
View issue in JIRA: [WEBUI-28](https://jira.nuxeo.com/browse/WEBUI-28): Icon misalignment on document create

2020-09-03 14:52 UTC, richardsd commented
![copy_move_clipboard_buttons](https://user-images.githubusercontent.com/738700/92130944-3df1ff80-edfd-11ea-84a7-69c41c2ce865.gif)

2020-09-04 14:27 UTC, richardsd commented
Pretty much the approach I was following. There is no other way to detect changes in the array without listening for [splices](https://stackoverflow.com/questions/54599020/how-to-notify-array-mutation-to-parent-component-in-polymer-3).

2020-09-04 16:47 UTC, nmpcunha requested changes
It seems that the commit message has the wrong JIRA number

2020-09-07 08:08 UTC, richardsd commented
> It seems that the commit message has the wrong JIRA number

I am wondering what the heck happened here 🤔

2020-09-07 08:28 UTC, nmpcunha approved these changes

2020-09-07 09:07 UTC, semisse approved these changes

2020-09-07 11:14 UTC, merged