NXP-26628: refresh slot model when doc changes
nuxeo/nuxeo-web-ui pull request #1012
Opened 2020-09-04 15:52 UTC by richardsd

2020-09-04 15:52 UTC, nuxeojenkins commented
View issue in JIRA: [WEBUI-40](https://jira.nuxeo.com/browse/WEBUI-40): Display an error when trying to create a user which already exists

2020-09-04 16:41 UTC, semisse submitted a review, later dismissed

2020-09-04 16:45 UTC, nmpcunha approved these changes
The title is kind of misleading, but it is the backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1010 😅 

👍🏼

2020-09-04 16:47 UTC, nmpcunha requested changes
Just saw that you have the wrong ticket number. Same for the master branch PR

2020-09-07 08:28 UTC, nmpcunha approved these changes

2020-09-07 09:06 UTC, semisse approved these changes

2020-09-07 09:08 UTC, richardsd commented
Running the pipeline [here](https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/505/).

2020-09-07 11:14 UTC, merged