fix-NXP-28080-TasksInEndState
nuxeo/nuxeo-web-ui pull request #1047
Opened 2020-10-26 18:19 UTC by nmpcunha

👋🏼 

The idea was to try to have a "middle term" solution for this issue, since it was raised by Support and needs backporting.
Discussing with @carolinagouveia, we got to the this proposal. The idea was basically:
- "warn" the users that they are seeing a task that has already been processed;
- remove all the possible actions that have side effects;
- still display the information introduced by the user who processed the task, but on a "read only" kind of view;
- display actions that don't have an impact nor generate server side errors (e.g. "Show Graph" or user tag);

2020-10-26 18:19 UTC, nuxeojenkins commented
View issue in JIRA: [WEBUI-98](https://jira.nuxeo.com/browse/WEBUI-98): Fix Web UI view layout of ended task

2020-10-26 18:22 UTC, nmpcunha commented
The preview will help us to get a feeling of it, but this screenshot may also give you an idea 🙂 
![Screenshot 2020-10-26 at 18 21 45](https://user-images.githubusercontent.com/16035473/97212324-22c9bd80-17b8-11eb-9314-d0f87b5bc0ff.png)

2020-10-27 13:47 UTC, lisamcintyre commented
@nmpcunha , regarding the task and the focus of this, this looks good to me.  In a perfect world, the link to the item would be more "visible" to the user (and parhaps part of the message), but I don't think that is the function of this ticket, and more around the default task view and the header with the file name. and too, this is a default view, and can be configured 😄

2020-10-27 13:51 UTC, nmpcunha commented
> @nmpcunha , regarding the task and the focus of this, this looks good to me. In a perfect world, the link to the item would be more "visible" to the user (and parhaps part of the message), but I don't think that is the function of this ticket, and more around the default task view and the header with the file name. and too, this is a default view, and can be configured 😄

Thanks for the review.
Indeed! And we should keep in mind that workflow (and its tasks) can be related to multiple documents.
This to say that the feature that you are suggesting may need further investigation and proper requirements.

2020-10-27 13:52 UTC, lisamcintyre approved these changes
for this ticket, this looks good to me.  I notice some default view issues with this version of webui, but not part of this "task" 😄

2020-10-27 14:10 UTC, andreacornaglia commented on elements/workflow/nuxeo-document-task.js
> +                <paper-button
as Lisa was asking, shouldn't we include the styling for this? class="secondary"

2020-10-27 14:18 UTC, carolinagouveia requested changes

2020-10-27 14:18 UTC, carolinagouveia commented on i18n/messages.json
> +  "tasks.alreadyProcessed": "The task you are trying to seeing has already been completed. Please check the correspondent document for current status.",
We should change this message to "The task you are trying to _see_ (...)"

2020-10-27 14:19 UTC, nmpcunha commented on elements/workflow/nuxeo-document-task.js
> +                <paper-button
Since this is a support ticket, we can do that if we have clear guidelines. But, it is out of scope... so, it would be done on a separate commit and only for master.
Does anyone have clear instructions about this? @lisamcintyre , @andreacornaglia ?

2020-10-27 14:25 UTC, andreacornaglia commented on elements/workflow/nuxeo-document-task.js
> +                <paper-button
@nmpcunha makes sense! I think @carolinagouveia should take a look but IMO the "delegate" button should be secondary and so the "cancel review" (that now is primary).

2020-10-27 14:25 UTC, nmpcunha commented on i18n/messages.json
> +  "tasks.alreadyProcessed": "The task you are trying to seeing has already been completed. Please check the correspondent document for current status.",
🤦🏼 
Thanks! 😅

2020-10-27 14:36 UTC, Gabez0r reviewed
Great work. I just have a couple of questions:
1) I'm not sure the disclaimer on the top has enough emphasis.
2) Not sure if showing the "View Graph" action is very helpful, since it will show the graph as it is currently and not how it was when the task was still available. It might still make sense for consistency reasons ofc, but I was just wondering.

2020-10-27 14:36 UTC, Gabez0r commented on elements/workflow/nuxeo-document-task.js
> +        margin-bottom: 1rem;
Please double check with Carolina. This currently maps to 13px, and [I think it should either be 12px or 16px](https://nuxeowiki.atlassian.net/wiki/spaces/DT/pages/1091797171/Spacing).

2020-10-27 14:36 UTC, Gabez0r commented on elements/workflow/nuxeo-document-task.js
> +        margin-inline-end: 0.5rem;
Same here.

2020-10-27 14:36 UTC, Gabez0r commented on elements/workflow/nuxeo-document-task.js
> +          <div class$="[[_computeLayoutVisibility(task)]]">
Unfortunately, this does not prevent one from using the keyboard and reaching out to the elements and inputing data. I guess we should either:
1) avoid simulating this disabled state, as the fact that we can still input data can be considered a bug?
2) do the required work on nuxeo-layout so we can have a proper way to disable the fields

2020-10-27 14:48 UTC, carolinagouveia commented on elements/workflow/nuxeo-document-task.js
> +                <paper-button
As discussed with @nmpcunha, we'll apply the style of the text button for both "reassign" and "delegate" actions.

2020-10-27 14:55 UTC, nmpcunha commented on elements/workflow/nuxeo-document-task.js
> +                <paper-button
For the "Cancel Review", there is no possibility to to it.
The buttons (or actions) are retrieved from server side and they can be multiple (i.e. more than the usual two) since they are configured by the users on Studio side. This would imply a whole refactor, end-to-end, in order to give some field to the UI so we could know which kind of style to apply to which button.

2020-10-27 14:56 UTC, nmpcunha commented on elements/workflow/nuxeo-document-task.js
> +        margin-bottom: 1rem;
Double checked! We decided to keep like it is.
Thanks!

2020-10-27 14:59 UTC, nmpcunha commented on elements/workflow/nuxeo-document-task.js
> +          <div class$="[[_computeLayoutVisibility(task)]]">
Indeed!
Option _2_ is clearly out of scope, and TBH, not sure if we even want that balancing the use cases and the effort 🤷🏼‍♂️ 

It is true that the users can use the keyboard to access the fields (it is a matter of a visual styling to, somehow simulate that they are disabled). Anyway, guess this is a decision to @lisamcintyre and/or @carolinagouveia.
I don't expect a lot of problems with that and if we receive a bug stating that we can change the values using the keyboard, guess we have arguments to explain it. Otherwise, we can go with the fields "active", but it seems to provide a worse UX.

Let's wait for more feedback on this! Thanks!

2020-10-27 15:15 UTC, carolinagouveia commented on elements/workflow/nuxeo-document-task.js
> +          <div class$="[[_computeLayoutVisibility(task)]]">
I do understand that option 2 is out of this ticket's scope but I prefer to do the required work and having the fields properly disabled, to avoid future issues.

2020-10-27 16:28 UTC, nmpcunha commented on elements/workflow/nuxeo-document-task.js
> +          <div class$="[[_computeLayoutVisibility(task)]]">
Does that mean that on this ticket we should remove the opacity and pointer events and let the fields be editable?
Or are you suggesting to keep the current approach (with opacity and pointer events disabled) and try to create a ticket to assess and schedule some work to have that ability on `nuxeo-layout`.

2020-10-27 16:38 UTC, carolinagouveia commented on elements/workflow/nuxeo-document-task.js
> +          <div class$="[[_computeLayoutVisibility(task)]]">
The second option, create the ticket to work on disabling it on nuxeo-layout.

2020-10-27 17:02 UTC, nmpcunha commented
Think I've covered all the suggestions and also added a 🎁  on the third commit (only for master), correcting a visual/styles bug.

Please let me know if it is ok from your side 👍🏼

2020-10-27 17:03 UTC, nmpcunha commented on elements/workflow/nuxeo-document-task.js
> +          <div class$="[[_computeLayoutVisibility(task)]]">
Thanks!
I've kept that piece of code.

Regarding the ticket creation, @Gabez0r how do you want us to contribute on that? (cc @lisamcintyre)

2020-10-27 19:10 UTC, lisamcintyre reviewed
I just now took a look on the preview, different browsr than what I used before, so not cached, and I still see some of the requested changes not done (lile carolina's wording suggestion.  last note I see from Nuno says it was updated.  Did i miss something 😓 I even started a new task on a new item (knowing that wf changes might only appear on newly instantiated flows, or at least they used to).
<img width="1324" alt="Screen Shot 2020-10-27 at 2 05 12 PM" src="https://user-images.githubusercontent.com/18596875/97349947-1ac45900-185e-11eb-8e7d-81dd3b7e6052.png">

2020-10-28 09:46 UTC, andreacornaglia submitted a review, later dismissed

2020-10-28 11:06 UTC, semisse commented
Can you please consider the possibility of putting the icon and the message side-by-side, instead of wrapping the text around it? 
<img width="1324" alt="97349947-1ac45900-185e-11eb-8e7d-81dd3b7e6052" src="https://user-images.githubusercontent.com/1880896/97428266-a8ab4d00-190d-11eb-92aa-01eee2b2074f.png">

2020-10-28 11:51 UTC, nmpcunha commented
> Can you please consider the possibility of putting the icon and the message side-by-side, instead of wrapping the text around it?
> <img alt="97349947-1ac45900-185e-11eb-8e7d-81dd3b7e6052" width="1324" src="https://user-images.githubusercontent.com/1880896/97428266-a8ab4d00-190d-11eb-92aa-01eee2b2074f.png">

Hey! 👋🏼 

Done! Should be available when the preview up and running.
Had the need to define a `min-width` to the icon, just to try to don't expose the way this specific screen reacts to breakpoints. If you prefer to remove it, just let me know. (cc @carolinagouveia )

2020-10-28 13:22 UTC, carolinagouveia commented
> > Can you please consider the possibility of putting the icon and the message side-by-side, instead of wrapping the text around it?
> > <img alt="97349947-1ac45900-185e-11eb-8e7d-81dd3b7e6052" width="1324" src="https://user-images.githubusercontent.com/1880896/97428266-a8ab4d00-190d-11eb-92aa-01eee2b2074f.png">
> 
> Hey! 👋🏼
> 
> Done! Should be available when the preview up and running.
> Had the need to define a `min-width` to the icon, just to try to don't expose the way this specific screen reacts to breakpoints. If you prefer to remove it, just let me know. (cc @carolinagouveia )
> 
> Thank you!


I'm still seeing the old message on the latest preview.
![image](https://user-images.githubusercontent.com/29227905/97441277-73f4c100-1920-11eb-8ef9-bf4d7b1faa40.png)

2020-10-28 14:00 UTC, nmpcunha commented
Indeed @carolinagouveia , it seems that the preview generation for this repo has some issues. Seems to be stuck on the first version of things 😕 
Anyway, I'll wait for code review too, but please feel free to reach me for screenshots or quick demo.

2020-10-29 12:58 UTC, Gabez0r approved these changes

2020-10-29 12:59 UTC, mnixo approved these changes

2020-10-30 09:15 UTC, carolinagouveia approved these changes

2020-10-30 09:19 UTC, merged