ELEMENTS-1235: ensure 96px as min-height in nuxeo-dropzone
nuxeo/nuxeo-web-ui pull request #1049
Opened 2020-10-27 18:34 UTC by semisse

2020-10-27 18:34 UTC, nuxeojenkins commented
View issue in JIRA: [ELEMENTS-1235](https://jira.nuxeo.com/browse/ELEMENTS-1235): nuxeo-dropzone: change min-height to 48px

2020-10-29 10:08 UTC, mnixo approved these changes

2020-11-04 13:30 UTC, Gabez0r requested changes
LGTM, but please use a WEBUI ticket.

2020-11-05 16:53 UTC, semisse commented
I'm going to close this PR and replace it with a new one that also contains the new typography changes: https://github.com/nuxeo/nuxeo-web-ui/pull/1064

2020-11-05 16:53 UTC, closed without merging