NXP-29376: Add missing translations for nuxeo-document-history
nuxeo/nuxeo-web-ui pull request #1061
Opened 2020-11-04 16:52 UTC by RSalem07

2020-11-04 16:52 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29376](https://jira.nuxeo.com/browse/NXP-29376): Add missing translations for nuxeo-document-history

2020-11-04 18:14 UTC, nmpcunha approved these changes

2020-11-09 09:55 UTC, andreacornaglia approved these changes

2020-11-10 08:41 UTC, Gabez0r approved these changes

2020-11-10 08:56 UTC, Gabez0r requested changes
Sorry, but where are these labels used on master? I know they were required on 10.10, but I couldn't find a usage on master.

2020-11-10 09:15 UTC, nmpcunha commented
This PR is obsolete with the work being done under https://github.com/nuxeo/nuxeo-web-ui/pull/1063

2020-11-10 09:23 UTC, RSalem07 commented
@nmpcunha for your comment exactly, I was going to close it and give the link for the new PR for master

2020-11-10 09:23 UTC, closed without merging