Feat webui 111 nuxeo grid
nuxeo/nuxeo-web-ui pull request #1065
Opened 2020-11-06 18:00 UTC by Gabez0r

Please note that the scope of this ticket is just to add `nuxeo-grid`. All other changes are just for testing purposes.
TODO:
- [ ] Functional fests
- [ ] Document bug with video viewer
- [ ] Discuss value coercion
- [ ] Discuss hardcoded responsiveness

2020-11-06 18:00 UTC, nuxeojenkins commented
View issue in JIRA: [WEBUI-111](https://jira.nuxeo.com/browse/WEBUI-111): Create the grid element

2020-11-09 17:46 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +  cGrid.templateColumns = coerceValue(grid.templateColumns, /^(\d+fr|auto)$/, true, 'template-columns');
WDYT about this strategy to reduce the public API, so that we don't have to support the whole spectrum of CSS values?

2020-11-09 17:46 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +  /* --nuxeo-card-margin-bottom: 0; this will not work on all places and causes misalignments */
Right now we have a issue when using nuxeo cards, because they already have a margin bottom. This means that we usually only set a column gap and not a row gap to make up for this. But we should handle this better. Any ideas?

2020-11-09 17:46 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +    style += `${buildGridStyle(grid, '(max-width: 1024px)')}`;
I don't like it, but I can leave with a hardcoded media query, provided that we accept that we might have to introduce later a element property and/or global config property to control this behavior. WDYT?

2020-11-09 18:09 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +    };
Since this will only be attributes and not properties on elements, I don't think we have a good way to document them, so that this documentation can be leveraged on Designer. Any ideas?

2020-11-10 10:36 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +      cols: {
Should this be named `columns` instead, to be consisted with the other properties above?

2020-11-10 15:01 UTC, richardsd requested changes

2020-11-10 15:01 UTC, richardsd commented on elements/nuxeo-grid/nuxeo-grid.js
> +    style += `${buildGridStyle(grid, '(max-width: 1024px)')}`;
I agree with you, we can later deal with it. And how about putting this behavior toggleable? Do you think people would actually disable the default behavior? I think that most people will be happy with the default media query and won't disable it, but maybe it could be useful for a minority. WDYT?

2020-11-11 12:40 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +    style += `${buildGridStyle(grid, '(max-width: 1024px)')}`;
I also think most people will be OK with it. But there's always the exception...

2020-11-11 12:49 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +    return this.el.getAttribute(Child.ATTRS.COL) || '';
We can, but we still have the exception of the get id, which does not fallback to ''. So we cannot include the ` || ''` on this method, or it would have to be configurable.

2020-11-11 12:50 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +       * Default item alignment on the block axis (typically vertical). Can be `stretch`, `center`, `stard` and `end`.
The best we could do would be to annotate this with jsdoc. Are we able to read these back from the comments on Desginer?

2020-11-11 15:04 UTC, richardsd commented on elements/nuxeo-grid/nuxeo-grid.js
> +    style += `${buildGridStyle(grid, '(max-width: 1024px)')}`;
We can always expose the toggle, if it makes up for the exception 😄

2020-11-11 15:05 UTC, richardsd commented on elements/nuxeo-grid/nuxeo-grid.js
> +    return this.el.getAttribute(Child.ATTRS.COL) || '';
Oh, you're right. Didn't notice the `id` was different. In this case, maybe we don't need to introduce the method, since we cannot include the `||` 🤷‍♂️

2020-11-11 15:06 UTC, richardsd commented on elements/nuxeo-grid/nuxeo-grid.js
> +       * Default item alignment on the block axis (typically vertical). Can be `stretch`, `center`, `stard` and `end`.
I think it will depend on the structure we adopt to annotate the property.

2020-11-11 15:46 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +    style += `${buildGridStyle(grid, '(max-width: 1024px)')}`;
But we should rather expose this later right? When we actually know the use case and know if this needs to be local or global config.

2020-11-11 18:53 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +      COLUMN: 'nuxeo-grid-column',
I guess that we should not be naming it this way if we ever want to use native elements (divs for example). A div with a custom attribute works just fine, but it is not valid html and would fail on a validator. We should use a `data-*` attribute instead here, but I guess it will make the name more verbose. Also, I'm not sure how much of a problem this actually is, since we probably a lot of more stuff going on that would result in invalid html.

2020-11-12 09:55 UTC, richardsd submitted a review, later dismissed

2020-11-12 12:00 UTC, mnixo commented on elements/nuxeo-grid/nuxeo-grid.js
> +      COLUMN: 'nuxeo-grid-column',
I'd vote for replacing `nuxeo-*` with `data-*`, if that means being compliant with the spec. Although not very pretty, it shouldn't make much of a difference, and it's not like the `nuxeo-*` prefix was doing much anyway.

2020-11-12 12:08 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +      COLUMN: 'nuxeo-grid-column',
I agree. Thank you. I will create a poll on slack to decide what to replace, since I have seen people in favor of other approaches.

2020-11-12 18:33 UTC, mnixo approved these changes
👏

2020-11-13 11:44 UTC, nelsonsilva commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/document/gridfile/nuxeo-gridfile-create-layout.html
> +        data-column="1"
we could omit the explict row and column for these two, right?
could be nice to do so here to be sure things don't break in such cases

2020-11-13 11:44 UTC, nelsonsilva commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/nuxeo-document-sidebar.html
> +    <div class="side">
can we drop this wrapper div and move the styles to `:host`?

2020-11-13 11:44 UTC, nelsonsilva commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/nuxeo-document-sidebar.html
> +              readonly="[[!isTaggable(document)]]"
As this is a boolean shouldn't we be using `readonly$=[[..]]` here ?

2020-11-13 11:44 UTC, nelsonsilva commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/nuxeo-document-sidebar.html
> +        if (window.matchMedia('(min-width: 1024px)').matches && this.expandedWidth && this.opened) {
we're observing the size of the element but doing responsiveness based on window size ? 🤔

2020-11-13 11:44 UTC, nelsonsilva commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/nuxeo-document-sidebar.html
> +    Polymer({
Shouldn't we be using class syntax here ?

2020-11-13 11:44 UTC, nelsonsilva commented on elements/nuxeo-grid/nuxeo-grid.js
> +      COLUMNSPAN: 'data-columnspan',
i know we've reviewed these already but now looking at it I feel this should be `data-column-span` and `data-row-span` for consistency, wdyt?

2020-11-13 11:44 UTC, nelsonsilva commented on elements/nuxeo-grid/nuxeo-grid.js
> +  cGrid.templateColumns = validateValue(grid.templateColumns, /^(\d+fr|\d+px|auto)$/, validate, 'template-columns');
this makes me think we should have proper setters where we enforce the validation... if tricky to do with a Polymer element perhaps we could do at least with the `Child` class (which could be called `Cell`no? )

2020-11-13 11:44 UTC, nelsonsilva commented on elements/nuxeo-grid/nuxeo-grid.js
> +      CHILDID: 'data-child-id',
what's child id for ?

2020-11-13 11:44 UTC, nelsonsilva commented on elements/nuxeo-grid/nuxeo-grid.js
> +    const children = Array.from(this.querySelectorAll(':scope > *')).map((child) => new Child(child));
don't we normally use `slot.assignedNodes()` to get this ?

2020-11-13 11:44 UTC, nelsonsilva commented on elements/nuxeo-grid/nuxeo-grid.js
> +    const styleEl = document.createElement('style');
this looks weird to me... shouldn't we generate the style as part of the template function?

2020-11-13 13:16 UTC, Gabez0r commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/nuxeo-document-sidebar.html
> +    <div class="side">
I tried, but we started to get all sorts of artifacts. I spent way too much time trying to fix it, for an element that we are just keeping for testing purposes.

2020-11-13 13:17 UTC, Gabez0r commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/document/gridfile/nuxeo-gridfile-create-layout.html
> +        data-column="1"
Sure, why not!

2020-11-13 13:23 UTC, Gabez0r commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/nuxeo-document-sidebar.html
> +        if (window.matchMedia('(min-width: 1024px)').matches && this.expandedWidth && this.opened) {
Yes. This was an early prototype where I was still playing with with the ability of having responsiveness on this element, so we might have some mixed concepts here. I kept it here because it we might find it useful on how to do it later, but this is not used by the tests at all. Maybe it is better to just remove it?

2020-11-13 13:30 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +      CHILDID: 'data-child-id',
To generate the css rule for that element. E.g.:
```
::slotted([data-child-id="1"]) {
  grid-column: 1;
  grid-row: 1;
}
```

2020-11-13 13:36 UTC, Gabez0r commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/nuxeo-document-sidebar.html
> +    Polymer({
Eh... it's on a test project where anything else uses class based syntax. Nor did the original element use class based syntax. But I guess we can start doing it.

2020-11-13 13:54 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +  cGrid.templateColumns = validateValue(grid.templateColumns, /^(\d+fr|\d+px|auto)$/, validate, 'template-columns');
In the case of the Child, we are not even validating when we set, but when we get from the attributes instead. Wouldn't it be weird to enforce validation on a getter? And I fear that having it in one way for the Child and another way for the Grid will make the code harder to maintain.

> Child class (which could be called `Cell` no? )

Not necessarily, since a child can take multiple cells.

2020-11-13 14:10 UTC, richardsd commented on elements/nuxeo-grid/nuxeo-grid.js
> +      COLUMNSPAN: 'data-columnspan',
It also increases readability here. Maybe a good call.

2020-11-13 14:26 UTC, nelsonsilva commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/nuxeo-document-sidebar.html
> +        if (window.matchMedia('(min-width: 1024px)').matches && this.expandedWidth && this.opened) {
Just noticed this is in itest... Nevermind

2020-11-13 14:27 UTC, nelsonsilva commented on plugin/itests/addon/src/main/resources/web/nuxeo.war/ui/nuxeo-document-sidebar.html
> +    Polymer({
Same, just realized this is in itest so better keep ES5 syntax since it's what VD supports

2020-11-13 14:28 UTC, Gabez0r commented on elements/nuxeo-grid/nuxeo-grid.js
> +    const children = Array.from(this.querySelectorAll(':scope > *')).map((child) => new Child(child));
Need to be assignedElements, otherwise we will get text nodes as well. :grimacing:

2020-11-13 14:34 UTC, nelsonsilva commented on elements/nuxeo-grid/nuxeo-grid.js
> +      CHILDID: 'data-child-id',
Ah! I see 👍 Thought we were going with inline styles or some pseudo selector like nth-child or nth-of-type (not sure these work though)

2020-11-13 15:00 UTC, mnixo approved these changes

2020-11-13 15:56 UTC, richardsd commented on elements/nuxeo-grid/nuxeo-grid.js
> +    style += `${buildGridStyle(grid, '(max-width: 1024px)')}`;
Yes, you're right. We can do it later, when we have more information about the actual use case.

2020-11-13 16:05 UTC, richardsd approved these changes

2020-11-13 16:06 UTC, richardsd approved these changes

2020-11-13 16:25 UTC, merged