NXP-29579: add translations for retention addon
nuxeo/nuxeo-web-ui pull request #1073
Opened 2020-11-16 19:36 UTC by nmpcunha

2020-11-16 19:36 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29579](https://jira.nuxeo.com/browse/NXP-29579): Translate nuxeo-retention addon

2020-11-17 14:20 UTC, manonlumeau commented
Some of the labels are still in Engish even if the translation is available on Master and so Crowdin. 

Some examples of inconsistencies: 
Spanish:
1010 example: https://github.com/nuxeo/nuxeo-web-ui/pull/1073/files#diff-c344a3b4e645043d68e618fad0aeb546800eca1b8b5bef1771242f5c3430b6c9R27
Same label on master: https://github.com/nuxeo/nuxeo-web-ui/blob/master/i18n/messages-es-ES.json#L28

2020-11-17 14:31 UTC, manonlumeau requested changes

2020-11-17 14:31 UTC, manonlumeau commented on i18n/messages-fr.json
> +  "eventType.afterMakeRecord": "Declared as a record",
Translation on master: https://github.com/nuxeo/nuxeo-web-ui/blob/master/i18n/messages-fr.json#L560

2020-11-17 14:31 UTC, manonlumeau commented on i18n/messages-ar.json
> +  "activity.afterExtendRetention": "Retention period updated",
See comment on main page about this file.

2020-11-17 14:31 UTC, manonlumeau commented on i18n/messages-es-ES.json
> +  "app.document.unhold": "Legal hold removed",
Translation on master: https://github.com/nuxeo/nuxeo-web-ui/blob/master/i18n/messages-es-ES.json#L105

2020-11-17 16:30 UTC, nmpcunha commented
Thanks @manonlumeau for the review. Since this kind of work is a little bit error prone (copy/paste) it is always good to have other 👀  looking at it. Much appreciated 🙂 

Hope I've tackled all the issues found.

2020-11-17 18:57 UTC, manonlumeau approved these changes

2020-11-18 17:48 UTC, mnixo approved these changes

2020-11-18 17:55 UTC, merged