NXP-29837: handle a password on easyshare
nuxeo/nuxeo-web-ui pull request #1107
Opened 2020-12-08 13:45 UTC by s-guillaume

Features :
- Secure Easyshare shared folder with a password from Web-UI available on creation or edit layouts

- On a secured Easyshare shared folder, when a « public » end-user is accessing a secured Easyshare shared folder, it will be prompt the accessCode

- If the « public » end-user entered the defined accessCode, he will have access to the shared folder content from the current browser. 
=> Some extra informations will be added the your browser URL
=> These extra informations are mandatory once connected and cannot be removed or shared to other « public » end-users (these informations are dynamically changed on each call with a matching based on browser JSESSIONID so using another browser will imply to re-enter accessCode or share it, notice it’s not working with Incognito session on Browsers)

- AccessCode is controled on each call that means if you change your accessCode in the EasyShare folder, previously connected users will be disconnected and prompted a new AccessCode

1.	Core/WebUI update

Two new metadatas as accessCodeRequired (Boolean) and accessCode (String) value added to existing easyshare schema (updated XSD)

WebUI Layouts (creation /edit) and JSF layout (creation/edit)
- Checkbox for accessCodeRequired metadata to activate password requirement on public EasyShare access
- Input text for accessCode to provide a password

Translation available in English/US, French, German and Spanish to check

2. Easyshare "public" access is not changing with no password

If EasyShare folder has no password set, access to public Easyshare remains available (no access code required so public access will remain as current version of EasyShare).

3. Capacity of checking checkbox "Access code required ?" and setting password to secure access to an Easyshare collection

If checkbox is checked, password is mandatory

4. Easyshare "public" access will ask for a password (access code) if the collection has password protected access (checkbox checked).
In that case, the user is prompted to enter the password. 

5. If the right password is entered, the user will be able to navigate in the collection. Otherwise, he must re-enter the password.
Notice all links are available for end-users include 3 new dynamic url parameters (a, s and j). They are calculated on the fly, encrypted with default and generated salt and only available on the current browser.

2020-12-08 13:45 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29837](https://jira.nuxeo.com/browse/NXP-29837): Handle a password on Easyshare

2020-12-08 13:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-web-ui?pullRequest=1107) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-web-ui?pullRequest=1107) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-web-ui?pullRequest=1107) it.</sub>

2021-01-12 09:49 UTC, Gabez0r requested changes
Commits to the `nuxeo-web-ui` repo require a WEBUI Jira ticket. Please create one and amend the commit message.

2021-01-12 09:49 UTC, Gabez0r commented on i18n/messages-de.json
> +  "easysharefolder.accessCodeRequired": "Zugangscode erforderlich?",
On master, you only need to add labels to `messages.json`. All other messages files will be overridden once labels are synched with Crowdin.

2021-01-12 09:49 UTC, Gabez0r commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +        document: Object
The dangling comma was removed, which will cause linting to fail.

2021-01-15 17:24 UTC, Gabez0r commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +      on-value-changed="checkAccessCode"
We should be able to achieve similar behavior without needing `checkAccessCodeRequired` and `checkAccessCode`, by changing:
```suggestion
      required="[[document.properties.eshare:accessCodeRequired]]"
```

2021-01-15 17:24 UTC, Gabez0r commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-edit-layout.html
> +      on-value-changed="checkAccessCode"
Same here.

2021-01-21 10:06 UTC, Gabez0r commented
Depends on https://github.com/nuxeo/nuxeo/pull/4520.

2021-01-21 15:28 UTC, andreacornaglia commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +      [[i18n('easysharefolder.accessCodeRequired')]]
can we format this as one property per line?

2021-01-21 15:59 UTC, andreacornaglia commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +      checkAccessCode: function(event) {
seems like we're not using the event argument passed to the function, should we remove it?

2021-01-21 16:00 UTC, andreacornaglia commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-edit-layout.html
> +      checkAccessCode: function(event) {
here too seems like we're not using event.

2021-01-21 16:49 UTC, andreacornaglia commented
@s-guillaume thanks for your work! @Gabez0r and I left some comments. Let us know if it makes sense or you need further info.

2021-01-26 14:30 UTC, s-guillaume commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +      [[i18n('easysharefolder.accessCodeRequired')]]
On existing widget 10 lines above (for paper-checkbox name="notification" ...) do I need to apply the same (one property per line) as this widget was previously done by Nuxeo ?

2021-01-26 14:34 UTC, s-guillaume commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +      [[i18n('easysharefolder.accessCodeRequired')]]
> can we format this as one property per line?

On existing widget 10 lines above (for paper-checkbox name="notification" ...) do I need to apply the same (one property per line) as this widget was previously done by Nuxeo ?

2021-01-26 18:01 UTC, s-guillaume commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +      on-value-changed="checkAccessCode"
OK, tested as expected but regarding checkAccessCodeRequired method launched on-tap, the accessCode input is also changing untapping the checkbox (passing from red to blue and removing the required red star). Do I also need to remove it ?

2021-01-27 08:40 UTC, s-guillaume commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +      checkAccessCode: function(event) {
You're right, done and tested.

2021-01-27 09:05 UTC, s-guillaume commented on i18n/messages-de.json
> +  "easysharefolder.accessCodeRequired": "Zugangscode erforderlich?",
2 entries (easysharefolder.accessCodeRequired and easysharefolder.accessCode) removed from fr, de and es JSON files

2021-01-27 11:18 UTC, Gabez0r commented on i18n/messages-de.json
> +  "easysharefolder.accessCodeRequired": "Zugangscode erforderlich?",
Yes, that's it. Thank you.

2021-02-02 10:33 UTC, andreacornaglia commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +      [[i18n('easysharefolder.accessCodeRequired')]]
@s-guillaume no, just formatting the code you modify is fine :)

2021-02-02 10:36 UTC, andreacornaglia commented
@s-guillaume thank you for considering our comments. The code LGTM but I would modify the commit message to state what the code is doing instead. ("add the option of password protection via easyshare" or something along those lines). Thanks!

2021-02-02 10:50 UTC, Gabez0r commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +        this.$.accessCode.required = event.target.checked;
@s-guillaume: why do we need this? I would expect the `required="[[document.properties.eshare:accessCodeRequired]]"` to already have this behavior.

2021-02-03 14:27 UTC, s-guillaume commented on addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-create-layout.html
> +        this.$.accessCode.required = event.target.checked;
Removed, you're right

2021-02-08 14:49 UTC, s-guillaume commented
> Commits to the `nuxeo-web-ui` repo require a WEBUI Jira ticket. Please use [WEBUI-189](https://jira.nuxeo.com/browse/WEBUI-189) instead and amend the commit message.

Done

2021-02-08 14:49 UTC, closed without merging