NXP-28893: poll for pages before showing 404
nuxeo/nuxeo-web-ui pull request #1110
Opened 2020-12-10 17:52 UTC by nelsonsilva

2020-12-10 17:52 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-28893](https://jira.nuxeo.com/browse/NXP-28893): User gets "404 Not found" error when refreshing Retention management pages

2020-12-11 09:33 UTC, richardsd submitted a review, later dismissed

2020-12-14 17:16 UTC, semisse submitted a review, later dismissed

2020-12-15 09:40 UTC, Gabez0r requested changes
Please move this to a WEBUI ticket and amend the commit. 🙏

2020-12-15 18:20 UTC, nelsonsilva commented
> Please move this to a WEBUI ticket and amend the commit. 🙏

Done 👍

2020-12-16 09:07 UTC, richardsd approved these changes, later dismissed

2020-12-16 11:19 UTC, semisse submitted a review, later dismissed

2021-01-06 16:16 UTC, Gabez0r approved these changes, later dismissed

2021-02-25 10:26 UTC, Gabez0r approved these changes

2021-10-21 14:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-web-ui?pullRequest=1110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-web-ui?pullRequest=1110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-web-ui?pullRequest=1110) it.</sub>

2022-02-18 15:18 UTC, Gabez0r commented
Closing this one, because the code was already integrated with https://github.com/nuxeo/nuxeo-web-ui/pull/1264.

2022-02-18 15:18 UTC, closed without merging