WEBUI-181: add nuxeo-app-top var into consideration for height and po…
nuxeo/nuxeo-web-ui pull request #1148
Opened 2021-02-02 16:15 UTC by andreacornaglia

…sition of elements on web ui

2021-02-02 17:22 UTC, richardsd requested changes
It looks good 👍 
Doing some experiments, I think there are some missing places where we need to add the `nuxeo-app-top` for the calculations, like [here](https://github.com/nuxeo/nuxeo-web-ui/blob/master/elements/search/nuxeo-search-form.js#L56), wdyt?
![Screenshot 2021-02-02 at 17 16 12](https://user-images.githubusercontent.com/738700/106637969-3f298300-657b-11eb-8137-022f2a1f1038.png)
(there is an extra scrollbar in the search form)

2021-02-03 12:22 UTC, semisse commented
Please, also check `nuxeo-expired-session` and `nuxeo-offline-banner`

2021-02-05 10:08 UTC, andreacornaglia commented
@richardsd and @semisse thanks for the suggestions! I added them into the PR, let me know if it looks good.

2021-02-05 10:27 UTC, semisse commented on elements/nuxeo-app/nuxeo-expired-session.js
> -        visibility: hidden;
Please, do not remove this line

2021-02-05 10:28 UTC, semisse commented on elements/nuxeo-app/nuxeo-expired-session.js
> +        top: var(--nuxeo-app-top);
I think we should add the default value here, to make it more robust
```suggestion
        top: var(--nuxeo-app-top, 0px);
```

2021-02-05 10:29 UTC, semisse requested changes
Please, add back the visibility propriety in the `nuxeo-expired-session`, otherwise, it will be always displayed.

2021-02-05 10:33 UTC, semisse commented on elements/nuxeo-app/nuxeo-expired-session.js
>          -webkit-transform: translateY(-100%);
Can you please consider removing this obsolete line? 🙏 
```suggestion
        -webkit-transform: translateY(-100%);
```

2021-02-05 10:46 UTC, semisse commented on elements/nuxeo-app/nuxeo-expired-session.js
>          transform: translateY(-100%);
We actually need to do some calculations here as well, otherwise, this banner will not be inside `nuxeo-app`, something like this (feel free to change it if you feel it can be more readable):
```suggestion
        transform: translateY(calc(-(100%) - (--var(--nuxeo-app-top, 0))));
```

2021-02-05 10:58 UTC, semisse commented on elements/nuxeo-app/nuxeo-expired-session.js
>          transform: translateY(-100%);
Same thing on `nuxeo-offline-banner`

2021-02-05 11:13 UTC, semisse commented
Nice job 💪 
Don't forget to also apply these changes to `3.0.x` and `10.10`. If you need any help, please ping me.

2021-02-05 14:22 UTC, andreacornaglia commented on elements/nuxeo-app/nuxeo-expired-session.js
> -        visibility: hidden;
haha ooops thanks for the catch

2021-02-05 14:23 UTC, andreacornaglia commented on elements/nuxeo-app/nuxeo-expired-session.js
> +        top: var(--nuxeo-app-top);
agreed! will add a default value for the var occurrences

2021-02-05 14:26 UTC, andreacornaglia commented on elements/nuxeo-app/nuxeo-expired-session.js
>          transform: translateY(-100%);
makes sense. I'm not sure what exactly this transform is doing. Do we need this property?

2021-02-05 15:41 UTC, semisse commented on elements/nuxeo-app/nuxeo-expired-session.js
>          transform: translateY(-100%);
we do, it is responsible for creating a slide animation from top to bottom, which is something that we've been doing for several versions now, so I think it is expected for us to maintain it.

2021-02-05 15:43 UTC, andreacornaglia commented on elements/nuxeo-app/nuxeo-expired-session.js
>          -webkit-transform: translateY(-100%);
done

2021-02-08 13:55 UTC, andreacornaglia commented
> Nice job 💪
> Don't forget to also apply these changes to `3.0.x` and `10.10`. If you need any help, please ping me.

Thanks! I added the PRs:

3.0.x https://github.com/nuxeo/nuxeo-web-ui/pull/1152
10.10 https://github.com/nuxeo/nuxeo-web-ui/pull/1151

2021-02-08 14:38 UTC, mnixo submitted a review, later dismissed

2021-02-08 16:28 UTC, semisse commented on elements/nuxeo-suggester/nuxeo-suggester.js
> +        top: var(--nuxeo-app-top, 0);
we should remove the `top` propriety applied here and move it to its parent (`#suggester`)
 ```suggestion
#suggester {
        top: var(--nuxeo-app-top, 0);
        left: 0;
        position: fixed;
        z-index: 1001;
        width: 100%;
        height: 100%;
        @apply --layout-vertical;
        @apply --layout-center;
      }
```

We should also remove the `position` propriety

2021-02-08 17:21 UTC, richardsd approved these changes

2021-02-08 17:21 UTC, richardsd commented on elements/nuxeo-app/nuxeo-expired-session.js
> -        -webkit-transform: translateY(-100%);
We no longer need the `--webkit-transform`?

2021-02-08 17:21 UTC, richardsd commented
It looks good 👍

2021-02-09 10:08 UTC, andreacornaglia commented on elements/nuxeo-app/nuxeo-expired-session.js
> -        -webkit-transform: translateY(-100%);
according to @semisse , no https://github.com/nuxeo/nuxeo-web-ui/pull/1148#discussion_r570872574

2021-02-09 10:08 UTC, andreacornaglia commented on elements/nuxeo-suggester/nuxeo-suggester.js
> +        top: var(--nuxeo-app-top, 0);
great suggestion for the suggester :) done.

2021-02-09 10:53 UTC, richardsd commented on elements/nuxeo-app/nuxeo-expired-session.js
> -        -webkit-transform: translateY(-100%);
Thanks 👍

2021-02-09 12:27 UTC, mnixo submitted a review, later dismissed

2021-02-10 10:42 UTC, richardsd submitted a review, later dismissed

2021-02-10 14:32 UTC, semisse approved these changes

2021-02-10 14:36 UTC, semisse requested changes
Please align the commit message with the other backport PR's. I would suggest actually using the formulation you did on the other PR's:
`WEBUI-181: adjust elements to nuxeo-app-top`

2021-02-10 15:31 UTC, semisse approved these changes

2021-02-11 10:11 UTC, mnixo approved these changes

2021-02-11 11:25 UTC, merged