WEBUI-315: backport coldstorage infobar into 10.10
nuxeo/nuxeo-web-ui pull request #1208
Opened 2021-04-15 18:13 UTC by andreacornaglia

2021-04-15 18:14 UTC, nuxeojenkins commented
View issue in JIRA: [WEBUI-315](https://jira.nuxeo.com/browse/WEBUI-315): Backport Colstorage Infobar to 10.10

2021-04-16 07:33 UTC, doulba approved these changes

2021-04-16 07:40 UTC, RSalem07 commented
@andreacornaglia I think we should get some feedbacks from UI team. It seems this part wasn't extracted even for LTS and master for our two addons: retention and cold storage.
Retention => https://github.com/nuxeo/nuxeo-web-ui/blob/master/elements/nuxeo-document-info-bar/nuxeo-document-info-bar.js#L191-L197
Cold Storage => https://github.com/nuxeo/nuxeo-web-ui/blob/master/elements/nuxeo-document-info-bar/nuxeo-document-info-bar.js#L130-L150

For me the idea when the addons were extracted is to be more independent from the others release as much as possible. We should be able to contribute to the bar info elements. I don't think it's possible with what we have. Could you sync avec UI team, if needed we will create a UI ticket to make this part configurable, perhaps the same logic than the slots https://github.com/nuxeo/nuxeo-retention/blob/lts-2021/nuxeo-retention-web/nuxeo-retention.html#L67-L75

2021-04-19 09:25 UTC, Gabez0r requested changes

2021-04-19 09:25 UTC, Gabez0r commented on i18n/messages.json
> +  "documentPage.content.storedInColdStorage": "The master file is stored in cold storage.",
Please backport the labels as well for other languages, or we will be missing translations on 10.10.

2021-04-19 13:53 UTC, andreacornaglia commented on i18n/messages.json
> +  "documentPage.content.storedInColdStorage": "The master file is stored in cold storage.",
ok, done.

2021-04-19 14:00 UTC, doulba approved these changes

2021-04-19 14:21 UTC, Gabez0r approved these changes

2021-04-19 14:41 UTC, merged