Clean up web UI 222 remove retention check for deletion 10.10
nuxeo/nuxeo-web-ui pull request #1305
Opened 2021-09-23 15:51 UTC by guirenard

2021-09-23 15:51 UTC, nuxeojenkins commented
View issues in JIRA:
- [WEBUI-37](https://jira.nuxeo.com/browse/WEBUI-37): Update Web UI elements to use RemoveChildren permission
- [WEBUI-222](https://jira.nuxeo.com/browse/WEBUI-222)

2021-09-24 12:26 UTC, guirenard commented
Pipeline successful https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/933/

2021-09-24 13:22 UTC, mnixo approved these changes, later dismissed

2021-09-28 09:49 UTC, andreacornaglia approved these changes, later dismissed

2021-09-28 10:56 UTC, richardsd requested changes

2021-09-28 10:56 UTC, richardsd commented on elements/nuxeo-document-bulk-actions/nuxeo-delete-documents-button.html
>         * Checks if a single given document has 'Everything' permission to delete or 'Write' to trash
Maybe we should update the description of the method, since now it only checks for the `Remove` permission.

2021-09-28 13:15 UTC, mnixo approved these changes

2021-09-28 14:03 UTC, richardsd approved these changes

2021-09-28 14:06 UTC, merged