WEBUI-552: better total count display
nuxeo/nuxeo-web-ui pull request #1318
Opened 2021-10-26 15:16 UTC by guirenard

2021-10-26 15:16 UTC, nuxeojenkins commented
View issue in JIRA: [WEBUI-552](https://jira.nuxeo.com/browse/WEBUI-552): Adapt results count displayed in nuxeo-results when total count is unknown

2021-10-26 15:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/nuxeo/nuxeo-web-ui?pullRequest=1318) <br/>All committers have signed the CLA.

2021-10-26 15:16 UTC, guirenard commented
Depends on https://github.com/nuxeo/nuxeo-lts/pull/278

2021-10-29 16:25 UTC, semisse commented on elements/nuxeo-results/nuxeo-results.js
> +            >[[_resultsCountLabel]]</span
can we fix this weird indentention?
```suggestion
            >[[_resultsCountLabel]]</span>
```

2021-10-29 16:25 UTC, semisse submitted a review, later dismissed

2021-11-02 10:02 UTC, richardsd approved these changes, later dismissed

2021-11-02 10:02 UTC, richardsd commented on i18n/messages.json
> +  "results.heading.count.unknonw": "Many results",
Since you're introducing a new key, please don't forget to create the ticket to handle the translations (see [NXDOC-2351](https://jira.nuxeo.com/browse/NXDOC-2351) or [NXDOC-2382](https://jira.nuxeo.com/browse/NXDOC-2382).

2021-11-05 16:33 UTC, carolinagouveia commented
The label as "Many results" is ok by me. No impediments on UX side.

2021-11-09 16:32 UTC, manonlumeau commented on i18n/messages.json
> +  "results.heading.count.unknonw": "Many results",
Hi @richardsd! I created [NXDOC-2395](https://jira.nuxeo.com/browse/NXDOC-2395) following your comment.

2021-11-22 17:34 UTC, mnixo submitted a review, later dismissed

2021-12-08 17:28 UTC, guirenard commented
format/indent

2021-12-09 10:31 UTC, richardsd submitted a review, later dismissed

2021-12-14 10:46 UTC, mnixo approved these changes, later dismissed

2021-12-20 11:59 UTC, Gabez0r requested changes

2021-12-20 11:59 UTC, Gabez0r commented on i18n/messages.json
> +  "results.heading.count.unknonw": "Many results",
There a type here:
```suggestion
  "results.heading.count.unknown": "Many results",
```

2021-12-20 11:59 UTC, Gabez0r commented on elements/nuxeo-results/nuxeo-results.js
> +      ? this.i18n('results.heading.count.unknonw')
```suggestion
      ? this.i18n('results.heading.count.unknown')
```

2021-12-20 12:01 UTC, Gabez0r reviewed
Good work!

2021-12-28 17:49 UTC, guirenard commented
fix typo :eyes:

2021-12-29 14:30 UTC, mnixo approved these changes

2021-12-30 10:41 UTC, richardsd approved these changes

2022-01-07 17:35 UTC, Gabez0r approved these changes

2022-01-11 09:25 UTC, merged