WEBUI-730/731: add designer catalog generator
nuxeo/nuxeo-web-ui pull request #1521
Opened 2022-07-15 14:16 UTC by richardsd

2022-08-17 17:05 UTC, poonamyadav252 reviewed
It looks nice for now.

2022-08-19 07:23 UTC, rakeshkumar1019 reviewed
It looks good.

2022-08-19 10:09 UTC, rakeshkumar1019 approved these changes, later dismissed

2022-08-26 10:01 UTC, swarnadipa-dev approved these changes, later dismissed
Looks good

2022-08-26 11:17 UTC, SnehalNaik-DEV approved these changes, later dismissed
Looks good

2022-08-29 06:23 UTC, rakeshkumar1019 requested changes

2022-08-29 06:23 UTC, rakeshkumar1019 commented on .github/workflows/catalog.yaml
> +        description: 'Classifier to generate a custom catalog version for testing purposes'
here also missed `.`.
 description: 'Classifier to generate a custom catalog version for testing purposes`.`'

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/10.10/catalog-packages.json
> +      "description":"Nuxeo elements for building custom data visualization applications and dashboards"
here also 
"description":"Nuxeo elements for building custom data visualization applications and dashboards`.`"

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/10.10/catalog-packages.json
> +      "description":"Nuxeo Web UI default elements",
"description":"Nuxeo Web UI default elements`.`"

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/11.1/catalog-packages.json
> +      "description":"Nuxeo elements for building custom data visualization applications and dashboards"
"description":"Nuxeo elements for building custom data visualization applications and dashboards`.`"

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/11.1/catalog-packages.json
> +      "description":"Nuxeo Web UI default elements",
"description":"Nuxeo Web UI default elements`.`"

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/11.3/catalog-packages.json
> +      "description":"Nuxeo elements for building custom data visualization applications and dashboards"
"description":"Nuxeo elements for building custom data visualization applications and dashboards`.`"

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/11.3/catalog-packages.json
> +      "description":"Nuxeo Web UI default elements",
"description":"Nuxeo Web UI default elements`.`"

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/8.10/catalog-packages.json
> +      "description":"Nuxeo elements for building custom data visualization applications and dashboards"
"description":"Nuxeo elements for building custom data visualization applications and dashboards`.`"

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/8.10/catalog-packages.json
> +      "description":"Nuxeo Web UI default elements",
"description":"Nuxeo Web UI default elements`.`"

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/9.10/catalog-packages.json
> +      "description":"Nuxeo elements for building custom data visualization applications and dashboards"
"description":"Nuxeo elements for building custom data visualization applications and dashboards`.`"

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/9.10/catalog-packages.json
> +      "description":"Nuxeo Web UI default elements",
"description":"Nuxeo Web UI default elements`.`"

2022-08-29 06:23 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/src/hints/generators/polymer-hint-generator.js
> +          if (property.params && property.params.length > 0) {
Suggestion : we can check both the conditions  using  `Array.isArray()` function.
`if (property.params && property.params.length > 0)` to `if (Array.isArray(property.params))`
for Reference : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

2022-08-29 08:31 UTC, richardsd commented on packages/nuxeo-designer-catalog/src/hints/generators/polymer-hint-generator.js
> +          if (property.params && property.params.length > 0) {
Yes we can, thanks @rakeshkumar1019

2022-08-30 14:10 UTC, richardsd commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/10.10/catalog-packages.json
> +      "description":"Nuxeo elements for building custom data visualization applications and dashboards"
To keep it consistent with the current behavior we already have in Designer (where these files are loaded), I don't think we need to add the `.` in the `*.json` files.

2022-08-31 07:16 UTC, rakeshkumar1019 commented on packages/nuxeo-designer-catalog/data/applications/nuxeo/10.10/catalog-packages.json
> +      "description":"Nuxeo elements for building custom data visualization applications and dashboards"
Okay, thanks for letting me know.

2022-08-31 07:25 UTC, rakeshkumar1019 approved these changes, later dismissed
looks good to me.

2022-08-31 11:27 UTC, Gabez0r reviewed
LGTM

2022-08-31 11:27 UTC, Gabez0r commented on .github/workflows/catalog.yaml
> +        description: 'Classifier to generate a custom catalog version for testing purposes.'
Not sure what this is. Leaving a comment here could help.

2022-08-31 14:35 UTC, richardsd commented on .github/workflows/catalog.yaml
> +        description: 'Classifier to generate a custom catalog version for testing purposes.'
It is just a classifier used for naming the catalog package that is generated.
I can leave a comment here (or even remove it 🤔)

2022-08-31 14:59 UTC, Gabez0r commented on .github/workflows/catalog.yaml
> +        description: 'Classifier to generate a custom catalog version for testing purposes.'
In what situation do we need to change this?

2022-08-31 15:00 UTC, Gabez0r commented on .github/workflows/catalog.yaml
> +        description: 'Classifier to generate a custom catalog version for testing purposes.'
I'm ok with removing it if we don't plan on using it, or leaving a comment like "change this if you need to ..." for clarity

2022-08-31 15:03 UTC, richardsd commented on .github/workflows/catalog.yaml
> +        description: 'Classifier to generate a custom catalog version for testing purposes.'
This is used for testing. Imagine that you want to build a custom version of the catalog named `3.0.x-my-cool-catalog`, where the `my-cool-catalog` is the classifier

2022-08-31 15:04 UTC, Gabez0r commented on .github/workflows/catalog.yaml
> +        description: 'Classifier to generate a custom catalog version for testing purposes.'
It seems useful. Leaving that on a comment (or description even?) would help.

2022-08-31 15:49 UTC, richardsd commented on packages/nuxeo-designer-catalog/scripts/maven-deploy.sh
> +    MVN_REPO_URL=http://mavenin.nuxeo.com/nexus/content/repositories/public-snapshots
It should be updated to `https://packages.nuxeo.com` and `maven-public`

2022-09-06 10:40 UTC, Gabez0r approved these changes

2022-09-06 10:40 UTC, richardsd commented
Example PR generated by the workflow: https://github.com/nuxeo/nos/pull/1263

2022-09-06 15:29 UTC, mnixo approved these changes

2022-09-07 09:49 UTC, merged