WEBUI-841: createLayouts for UserWorkspaces
nuxeo/nuxeo-web-ui pull request #1539
Opened 2022-07-27 06:16 UTC by GuruprasadAnk1996

https://jira.nuxeo.com/browse/WEBUI-841

2022-07-27 06:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-web-ui?pullRequest=1539) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-web-ui?pullRequest=1539) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-web-ui?pullRequest=1539) it.</sub>

2022-07-27 12:09 UTC, rakeshkumar1019 commented on elements/document/userworkspacesroot/nuxeo-userworkspacesroot-edit-layout.html
> +`nuxeo-workspaceroot-create-layout`
file name and commented file name is different.

2022-07-27 12:12 UTC, rakeshkumar1019 commented on elements/document/userworkspacesroot/nuxeo-userworkspacesroot-metadata-layout.html
> +@element nuxeo-workspace-metadata-layout
here also, names in commented code & current file name is different.

2022-07-27 12:15 UTC, rakeshkumar1019 commented on elements/document/userworkspacesroot/nuxeo-userworkspacesroot-view-layout.html
> +@element nuxeo-workspace-view-layout
same here also, see[ here](https://github.com/nuxeo/nuxeo-web-ui/pull/1539/files#r930985817)

2022-07-27 12:17 UTC, rakeshkumar1019 requested changes
see above comments

2022-07-28 09:41 UTC, semisse commented
Please, also review your commits, since I think this can be in one single commit.

2022-07-28 09:50 UTC, semisse commented
Another thing: don't forget in the commit messages we use words spaced, like a regular sentence

2022-07-29 04:17 UTC, swarnadipa-dev approved these changes
Looks good

2022-07-29 05:18 UTC, SnehalNaik-DEV approved these changes
Looks good!

2022-07-29 08:40 UTC, closed without merging