WEBUI-104: add functional tests for document import with properties
nuxeo/nuxeo-web-ui pull request #1589
Opened 2022-09-06 08:55 UTC by Pranit-Sotre

https://jira.nuxeo.com/browse/WEBUI-104

2022-09-06 10:39 UTC, Nisha-QA reviewed
Since we have many new functions here you can create a new import_dialog.js file and move them

2022-09-06 10:39 UTC, Nisha-QA commented on ftest/features/import_doc.feature
> +    And I can see the inline nuxeo-image-viewer previewer
Add a step to validate the added properties

2022-09-06 10:39 UTC, Nisha-QA commented on ftest/features/import_doc.feature
> +    And I can see the inline nuxeo-image-viewer previewer
Here also, add a step to validate added properties

2022-09-06 10:39 UTC, Nisha-QA commented on ftest/features/import_doc.feature
> +  Scenario: Import a Document with adding properties
Nit: you can rephrase this to something like : Import a document with properties

2022-09-07 06:15 UTC, rakeshkumar1019 requested changes
make the changes suggested by @Nisha-QA Also, make sure the functional test check passes.

2022-09-07 06:38 UTC, Pranit-Sotre commented on ftest/features/import_doc.feature
> +  Scenario: Import a Document with adding properties
Done changes.

2022-09-07 08:51 UTC, Gabez0r requested changes
It's going in the right direction, good job!

2022-09-07 08:51 UTC, Gabez0r commented on ftest/features/import_doc.feature
> +    Then I select an asset type
A reader won't be able to tell what asset type was selected. This step should actually allow different asset types to be selected (e.g. `I select "Picture" asset type`)

2022-09-07 08:51 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui.js
> +  }
Here we are duplicating a bunch of code which is already available in the [document_layout](https://github.com/nuxeo/nuxeo-web-ui/blob/maintenance-3.0.x/packages/nuxeo-web-ui-ftest/pages/ui/browser/document_layout.js#L4-L28) page helper. We should instead have an helper inside the createDialog so that we can retried the (import) document layout and thus reuse the page wrapper methods we already have.

2022-09-07 08:51 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui.js
> +
This returns an arbitrary item (the 4th item), which makes the method obscure an unpredictable. In case we deploy a new document type, this will might return different results. Also, "asset" as a name does not help much in the context of the ui app. Such an helper would be better placed inside the createDialog.

2022-09-07 08:51 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui.js
> +
These should all be inside the createDialog (this.ui.createDialog), since we already have an abstraction for this.

2022-09-07 08:51 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
> +  driver.pause(3000); // XXX just give it some time to the server to do the conversions
This will render the test flaky. If you need to wait for longer, you can always wait for the toast message.

2022-09-07 08:51 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
> +Then('I can see the following properties:', function(table) {
Why do we need to create a new step and don't reuse the other step we already use to check properties after creating documents? https://github.com/nuxeo/nuxeo-web-ui/blob/maintenance-3.0.x/ftest/features/create_doc.feature#L51

2022-09-07 08:51 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
> +});
This should live inside the createDialog (this.ui.createDialog).

2022-09-09 06:54 UTC, Pranit-Sotre commented on packages/nuxeo-web-ui-ftest/pages/ui.js
> +  }
We are not using the existing function as xpath is different for create and import dialog box.

2022-09-09 06:57 UTC, Pranit-Sotre commented on packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
> +Then('I can see the following properties:', function(table) {
We need a new step as web element location is different when we import a document.

2022-09-09 09:44 UTC, richardsd commented
@Pranit-Sotre don't forget to rebase your branch. I see the `ftests` pr check failing on the install step (it could help).

2022-09-12 11:00 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
> +Then('I can see the following properties:', function(table) {
This step validates the metadata after navigating to the document that was just created, so I would not expect the element location to be different.

2022-09-12 11:00 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui.js
> +  }
I'm not following. You should have a helper that returns the a [DocumentLayout](https://github.com/nuxeo/nuxeo-web-ui/blob/maintenance-3.0.x/packages/nuxeo-web-ui-ftest/pages/ui/browser/document_layout.js#L4-L28) wrapping your import layout, which should allow you to reuse the helpers.

2022-09-12 11:00 UTC, Gabez0r commented on ftest/features/import_doc.feature
> +    And I can see the picture formats panel
nit: Missing newline at the end of the file

2022-09-12 11:00 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui/create_dialog.js
> +    return this.el.element('div[class="buttons horizontal justified layout"] paper-button.primary');
We should probably add a `name`, otherwise this will break if someone adjusts a class. for example.

2022-09-12 11:00 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui/create_dialog.js
> +    return this.el.element('iron-input input[placeholder="Select an asset type."]');
Same as above, adding a name or id here is preferable, since the placeholder name might change.

2022-09-12 11:00 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui/create_dialog.js
> +    return this.el.element('div[class="buttons horizontal justified layout"] paper-button.text:nth-child(3)');
Same as above, adding a name here is preferable.

2022-09-12 11:00 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui/create_dialog.js
> +  asset(val) {
This method should be named after what it does. For example, "selectAsset".

2022-09-13 11:23 UTC, Gabez0r reviewed
Looking good. We are almost there!

2022-09-13 11:23 UTC, Gabez0r commented on elements/document/nuxeo-document-import.js
> +            name="create"
There is already another button that does creation (with id="create"), so perhaps we could make this name more explicit to avoid any confusions. For example "createWithProperties" or something that tells that this is going to be used in the advanced scenario where we are adding properties.

2022-09-13 11:23 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui/create_dialog.js
> +
This is confusing because from this element, we can reach both "create" and "import" layouts. We have two options here:
1) Looking at the lines immediately above, I believe we could further extract this into a `DocumentImport` wrapper, which then could return the layout just have as you have here. This would also be consistent to what we are doing with DocumentCreate. This would allow us to move all the helpers we have below to this new wrapper.
2) Simpler option, but probably providing a more disperse API, to rename this method to "documentImportLayout".

2022-09-13 12:58 UTC, Nisha-QA approved these changes, later dismissed
Looks good

2022-09-13 13:34 UTC, rajatgoel-gl approved these changes, later dismissed

2022-09-14 08:30 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui/create_dialog.js
> +  selectAsset(val) {
I believe `selectAssetType` would be more appropriate even.

2022-09-14 08:30 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
> +  driver.waitForExist('#snackbarPanel mwc-snackbar[open] .mdc-snackbar__label', driver.options.waitForTimeout, true);
This just waits for the toast to be dismissed, but we are not even sure what message it was displaying, so this step might become flaky in some situations. We should wait to see the proper message on the toast that is displayed once the creation is complete.

2022-09-14 12:22 UTC, rakeshkumar1019 reviewed
Squash the last commit, it looks good.

2022-09-14 16:17 UTC, richardsd commented on packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
> +  driver.waitForExist('#snackbarPanel mwc-snackbar[open] .mdc-snackbar__label', driver.options.waitForTimeout, true);
I agree with @Gabez0r. We could probably do something like the following to assert that the message is displayed:

```js
  const notificationMessage = this.ui.getToastMessage(message);
  const trimmedMessage = message.trim().replace(/"/g, '');
  notificationMessage.should.be.equals(trimmedMessage);
```
Check https://github.com/nuxeo/nuxeo-web-ui/blob/maintenance-3.0.x/packages/nuxeo-web-ui-ftest/features/step_definitions/bulk_edit.js#L14-L18 for the context.

2022-09-14 16:17 UTC, richardsd requested changes
Please review your code based on @Gabez0r comment 🙂

2022-09-15 06:05 UTC, Pranit-Sotre commented on packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
> +  driver.waitForExist('#snackbarPanel mwc-snackbar[open] .mdc-snackbar__label', driver.options.waitForTimeout, true);
I have covered this point in import_doc.feature at line number 55 and 88.

2022-09-15 09:36 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
> +  driver.waitForExist('#snackbarPanel mwc-snackbar[open] .mdc-snackbar__label', driver.options.waitForTimeout, true);
Ok then this this line waiting for the  toast to disappear is redundant.

2022-09-15 10:15 UTC, FabioFSantos requested changes
Please review your code based on @Gabez0r last comment about the toast check redundancy, the rest looks good

2022-09-15 12:47 UTC, Pranit-Sotre commented on packages/nuxeo-web-ui-ftest/features/step_definitions/import_dialog.js
> +  driver.waitForExist('#snackbarPanel mwc-snackbar[open] .mdc-snackbar__label', driver.options.waitForTimeout, true);
Done

2022-09-15 13:16 UTC, richardsd approved these changes, later dismissed

2022-09-15 13:27 UTC, Nisha-QA approved these changes, later dismissed
Looks good

2022-09-15 18:36 UTC, FabioFSantos approved these changes, later dismissed

2022-09-16 09:00 UTC, rakeshkumar1019 approved these changes
looks good 👍

2022-09-16 09:41 UTC, richardsd approved these changes

2022-09-16 09:42 UTC, Gabez0r approved these changes

2022-09-16 09:42 UTC, FabioFSantos approved these changes

2022-09-19 09:15 UTC, pddgoncalves approved these changes

2022-09-19 09:53 UTC, Nisha-QA approved these changes
Looks good

2022-09-20 06:43 UTC, merged