WEBUI-424: fix full text input requiring Enter key press in Assets an…
nuxeo/nuxeo-web-ui pull request #1607
Opened 2022-09-28 11:27 UTC by GuruprasadAnk1996

https://jira.nuxeo.com/browse/WEBUI-424

2022-09-29 05:39 UTC, swarnadipa-dev approved these changes, later dismissed
Looks good

2022-09-30 06:40 UTC, rajatgoel-gl approved these changes, later dismissed

2022-09-30 09:02 UTC, Gabez0r reviewed
The solution solves the problem reported in the ticket, but it changes the behavior of the search:
1) **Before**: in auto mode, you had to press enter in full text search for the search to be executed.
2) **After**: in auto mode, search is performed automatically.

For me, the new behavior makes sense, but it is not consistent with what we have for other searches, including the default search. Please validate the change with @bchauvin first (or let me know if you already did).

2022-09-30 10:51 UTC, bchauvin commented
@Gabez0r @GuruprasadAnk1996 IIRC we requested people to use the enter key in the fulltext of auto search because otherwise typing would send too many requests to the server and create performance issues.

So, we have two options from here:
1. Remove the need to press enter in auto search but keep performance (maybe by using some kind of debounce or something?). If we do that, it needs to be consistent everywhere and not just in assets search.
=> it would certainly be appreciated by our customers, as long as performance is not impacted
=> scope might be bigger than what is requested in the support ticket, so maybe we could consider that as an improvement

2. Play it safe: keep the existing behavior that you need to press enter in auto search
=> solves the support ticket, so I would say it is ok and most likely the safest option to choose here

2022-09-30 13:23 UTC, Gabez0r commented
It is my understanding that we already have debouncers in place that prevent too many request to be made, so I wouldn't expect this to degrade performance, but I would recommend double checking.

2022-10-19 08:40 UTC, Gabez0r commented on elements/search/assets/nuxeo-assets-search-form.html
> +        this.set('params.ecm_fulltext', this.formatFulltext(this.searchTerm));
Do we need this here, since it is already done in `_search`?

2022-10-19 08:40 UTC, Gabez0r commented on elements/search/assets/nuxeo-assets-search-form.html
> +      on-change="_checkForEnter"
This is misleading because we are calling a method that was designed to handle a key press (`_checkForEnter`), and using it to just do a search. That probably why you are modifying `_checkForEnter` with logic that already exists inside `_search`. If we want to add the new behavior of always triggering the search, instead of only when pressing enter, please consider calling something else here, like `_search` directly.

2022-10-19 08:40 UTC, Gabez0r commented on elements/search/trash/nuxeo-trash-search-form.html
> +        );
See comments above.

2022-10-21 07:33 UTC, poonamyadav252 reviewed
Kindly try to close your `open comments`.

2022-10-27 05:13 UTC, rakeshkumar1019 requested changes

2022-10-27 05:13 UTC, rakeshkumar1019 commented on elements/search/assets/nuxeo-assets-search-form.html
> +      _showResults(e) {
In this function `_showResults(e)` I'm not sure what the purpose of writing if conditions is if we're calling the same `this. search()` inside as well.

2022-10-27 05:13 UTC, rakeshkumar1019 commented on elements/search/trash/nuxeo-trash-search-form.html
> +        this._search();
Here also same.

2022-10-28 04:33 UTC, swarnadipa-dev submitted a review, later dismissed
Looks good

2022-10-28 04:58 UTC, rakeshkumar1019 approved these changes, later dismissed
Looks good 👍.

2022-10-28 05:59 UTC, rajatgoel-gl submitted a review, later dismissed

2022-10-28 07:54 UTC, Gabez0r commented on elements/search/assets/nuxeo-assets-search-form.html
> -      on-keydown="_checkForEnter"
Is the `_checkForEnter` still used? If not, we should clean it up.

2022-10-28 07:54 UTC, Gabez0r commented on elements/search/trash/nuxeo-trash-search-form.html
> -      on-keydown="_checkForEnter"
Same as above.

2022-10-28 10:49 UTC, Gabez0r approved these changes

2022-10-28 10:53 UTC, rakeshkumar1019 approved these changes

2022-10-28 11:15 UTC, poonamyadav252 approved these changes
Looks fine to me.

2022-10-28 11:42 UTC, Nishant0928 approved these changes

2022-10-28 12:15 UTC, rajatgoel-gl approved these changes

2022-10-28 12:28 UTC, merged