WEBUI-424: fix full text input requiring enter key press( Backport 10.10)
nuxeo/nuxeo-web-ui pull request #1609
Opened 2022-09-29 06:29 UTC by GuruprasadAnk1996

https://jira.nuxeo.com/browse/WEBUI-424

2022-09-29 11:02 UTC, swarnadipa-dev submitted a review, later dismissed
Looks good

2022-09-29 11:12 UTC, SnehalNaik-DEV approved these changes, later dismissed
Looks good

2022-09-30 06:40 UTC, rajatgoel-gl submitted a review, later dismissed

2022-10-13 09:01 UTC, rakeshkumar1019 approved these changes, later dismissed
looks good 👍

2022-10-13 09:01 UTC, SnehalNaik-DEV approved these changes, later dismissed
Looks good.

2022-10-19 08:41 UTC, Gabez0r reviewed
Please see comments in https://github.com/nuxeo/nuxeo-web-ui/pull/1607#pullrequestreview-1147101310.

2022-10-21 07:10 UTC, rajatgoel-gl requested changes

2022-10-21 07:10 UTC, rajatgoel-gl commented on elements/search/trash/nuxeo-trash-search-form.html
> +                 on-change="_checkForEnter">
Gabriel Review comments are not implemented 
![WEBUI424](https://user-images.githubusercontent.com/94342965/197134714-a71eb931-a4d9-420b-88bb-39912269fbae.JPG)

2022-10-21 07:35 UTC, poonamyadav252 reviewed
please check your `open issues`.

2022-10-31 04:52 UTC, rakeshkumar1019 approved these changes
looks good.

2022-10-31 05:03 UTC, swarnadipa-dev approved these changes
Looks good

2022-10-31 05:08 UTC, Nishant0928 approved these changes

2022-10-31 14:11 UTC, Gabez0r approved these changes

2022-10-31 15:36 UTC, rajatgoel-gl approved these changes

2022-10-31 16:01 UTC, merged