WEBUI-928: analysis of import create button disabled feature
nuxeo/nuxeo-web-ui pull request #1623
Opened 2022-10-17 15:09 UTC by Nishant0928

2022-10-18 04:22 UTC, swarnadipa-dev commented on index.html
> +
Please remove extra lines and duplicate code

2022-10-18 04:22 UTC, swarnadipa-dev commented on elements/document/nuxeo-document-import.js
> +const flag = config.get('createDisabled.flag', false);
Please use a more meaningful name for the flag so that its easy to understand what it is doing.

2022-10-18 04:24 UTC, swarnadipa-dev requested changes
Please change the commit message to remove the word 'analysis', as this is not an analysis, but an implementation

2022-10-21 04:00 UTC, swarnadipa-dev submitted a review, later dismissed
Looks good

2022-10-21 07:25 UTC, poonamyadav252 reviewed
It is fine for me and don't forget to connect with Nisha to review the functionality.

2022-10-21 07:34 UTC, rajatgoel-gl requested changes
There are so many formatting changes have been introduced in the checking file. Kindly commit only changes that are required for the WEBUI-928

2022-10-27 07:27 UTC, Nishant0928 commented
> There are so many formatting changes have been introduced in the checking file. Kindly commit only changes that are required for the [WEBUI-928](https://jira.nuxeo.com/browse/WEBUI-928)

@rajatgoel-gl , the formatting changes have occured due to the prettier.

2022-10-27 10:42 UTC, poonamyadav252 requested changes
Kindly rebase your branch with maintenance.

2022-10-27 10:56 UTC, closed without merging