WEBUI-940: add functional tests to compare documents
nuxeo/nuxeo-web-ui pull request #1624
Opened 2022-10-21 05:27 UTC by Pranit-Sotre

2022-10-28 04:53 UTC, rakeshkumar1019 approved these changes, later dismissed
looks good 👍 .

2022-10-28 04:59 UTC, Nisha-QA submitted a review, later dismissed
Looks good

2022-10-28 08:12 UTC, poonamyadav252 approved these changes, later dismissed

2022-10-28 08:25 UTC, rajatgoel-gl approved these changes, later dismissed

2022-10-31 17:59 UTC, Gabez0r requested changes

2022-10-31 17:59 UTC, Gabez0r commented on packages/nuxeo-web-ui-ftest/pages/ui/browser.js
> +    return this.el.element('nuxeo-page div[class="header"]');
This helper is not specific enough and can return the wrong page. Consider adding the page element tagName to the query to make it more specific. Something like this:
```suggestion
    return this.el.element('nuxeo-diff-page div.header');
```

2022-11-01 13:40 UTC, rakeshkumar1019 approved these changes

2022-11-01 13:46 UTC, swarnadipa-dev approved these changes
Looks good

2022-11-02 04:55 UTC, Nisha-QA approved these changes
Looks good

2022-11-02 05:53 UTC, rajatgoel-gl approved these changes

2022-11-02 09:40 UTC, Gabez0r approved these changes

2022-11-02 10:32 UTC, merged