WEBUI-928: implementation of import create button disabled feature
nuxeo/nuxeo-web-ui pull request #1628
Opened 2022-10-27 11:05 UTC by Nishant0928

2022-10-27 12:56 UTC, rakeshkumar1019 approved these changes
Great work  👍 looks good to me.

2022-10-28 03:49 UTC, swarnadipa-dev approved these changes
Looks good

2022-10-28 06:46 UTC, SnehalNaik-DEV approved these changes
Looks Good.

2022-10-28 08:30 UTC, Gabez0r reviewed
I'm not convinced that this strategy satisfies what's on the description of the ticket:
> The Import documents have a default `Create` and 'Add property ' features. We need to find out whether we can disable the 'Create' button for the particulate user or not.

If it needs to depend on the user, how will a configuration property help?

From my point of view, the ticket asks whether it is possible or not to disable it, and the answer is "no, only with custom code on the project side, at the moment"; anything beyond that, it should be an improvement with clear specifications.

2022-10-28 08:30 UTC, Gabez0r commented on elements/document/nuxeo-document-import.js
> +      return this._getAllFiles().every((file) => 'checked' in file);
Here we are completely skipping `_canImport`, which verifies if the uploaded has completed. This means that the button to create will most likely be enabled even if the upload is still in progress, for example, which will most likely causes problems.

2022-10-28 08:33 UTC, Gabez0r requested changes
Please check my comments above.

2022-10-28 08:34 UTC, Gabez0r commented on elements/document/nuxeo-document-import.js
> +      return this._getAllFiles().every((file) => 'checked' in file);
Please double check this.

2022-10-28 08:47 UTC, nelsonsilva commented on elements/document/nuxeo-document-import.js
> +const createDisabled = config.get('importCreateDisabled.buttonDisabeled', false);
nit: typo on `buttonDisabled`
also you should probably rename `importCreateDisabled` to something more generic like, at least something like `importCreate`, that way you can add subproperties to it in the future if needed

2022-10-28 17:00 UTC, tmartins commented on elements/document/nuxeo-document-import.js
> +const createDisabled = config.get('importCreateDisabled.buttonDisabeled', false);
this typo was mentioned during our call this morning

2023-01-13 10:12 UTC, closed without merging