WEBUI-927: add functional tests for unselect some for publish action
nuxeo/nuxeo-web-ui pull request #1629
Opened 2022-10-27 12:51 UTC by Pranit-Sotre

2022-10-28 04:51 UTC, rakeshkumar1019 requested changes
Please investigate why the functional test is failing.

2022-10-28 05:47 UTC, swarnadipa-dev submitted a review, later dismissed
Looks good

2022-10-28 10:38 UTC, Nisha-QA commented on ftest/features/publication.feature
> +    Then I click the toast notification dismiss button
You can delete the line as this is causing intermittent failure in functional PR checks.

2022-10-28 12:26 UTC, GuruprasadAnk1996 approved these changes

2022-10-28 12:36 UTC, rakeshkumar1019 approved these changes

2022-10-28 12:40 UTC, rajatgoel-gl approved these changes

2022-10-31 04:30 UTC, Nisha-QA approved these changes
Looks good

2022-10-31 17:50 UTC, Gabez0r approved these changes

2022-11-01 07:36 UTC, merged