WEBUI-905: remove from favorites button should have a role and label
nuxeo/nuxeo-web-ui pull request #1630
Opened 2022-10-27 14:14 UTC by GuruprasadAnk1996

https://jira.nuxeo.com/browse/WEBUI-905

2022-10-28 04:18 UTC, swarnadipa-dev submitted a review, later dismissed
Looks good

2022-10-28 04:46 UTC, rakeshkumar1019 submitted a review, later dismissed
looks good 👍

2022-10-28 05:58 UTC, rajatgoel-gl approved these changes, later dismissed

2022-10-28 07:22 UTC, poonamyadav252 submitted a review, later dismissed

2022-10-28 07:52 UTC, Gabez0r requested changes, later dismissed

2022-10-28 07:52 UTC, Gabez0r commented on elements/nuxeo-collections/nuxeo-favorites.js
> +                  aria-label="removeFromFavorites"
aria-label is supposed to be human readable, so I don't think "removeFromFavorites" will help here.
cc @semisse .

2022-10-28 08:05 UTC, Gabez0r commented on elements/nuxeo-collections/nuxeo-favorites.js
> +                  aria-label="removeFromFavorites"
And it should also be localized (i.e. needs to be translated to the current language).

2022-10-28 08:26 UTC, semisse commented on elements/nuxeo-collections/nuxeo-favorites.js
> +                  aria-label="removeFromFavorites"
You are right, @Gabez0r.

2022-10-28 09:09 UTC, semisse commented on elements/nuxeo-collections/nuxeo-favorites.js
> +                  aria-label$="[[i18n('command.remove')]]"
Please be aware that this implementation may not be the most complete one, since adding the `role="button"` doesn't guarantee all the necessary interactivity that a native `button` brings out of the box. My suggestion would be to wrap this `iron-icon` under a `button` element, reset the style of the native button ([take as reference this PR](https://github.com/nuxeo/nuxeo-web-ui/commit/0c66615076cedfc186150205ac53135144f9f4f9) from @rakeshkumar1019) and add an `aria-hidden="true"` to the `iron-icon` itself.

2022-10-28 10:10 UTC, poonamyadav252 requested changes
Try to pass your ftest checks.

2022-10-28 12:03 UTC, Nishant0928 approved these changes

2022-10-28 12:04 UTC, rakeshkumar1019 approved these changes
looks good.
kindly resolve your open conversation.

2022-10-31 04:59 UTC, poonamyadav252 approved these changes

2022-10-31 05:01 UTC, swarnadipa-dev approved these changes
Looks good

2022-10-31 14:30 UTC, richardsd approved these changes

2022-10-31 15:39 UTC, rajatgoel-gl approved these changes

2022-11-01 05:39 UTC, Nisha-QA approved these changes
Looks good

2022-11-01 06:53 UTC, merged