WEBUI-517: make number of selected results announced by the screen reader
nuxeo/nuxeo-web-ui pull request #1638
Opened 2022-11-02 10:11 UTC by GuruprasadAnk1996

https://jira.nuxeo.com/browse/WEBUI-517

2022-11-02 12:18 UTC, rakeshkumar1019 approved these changes, later dismissed

2022-11-02 12:43 UTC, Nishant0928 submitted a review, later dismissed

2022-11-02 12:54 UTC, swarnadipa-dev approved these changes, later dismissed
Looks good

2022-11-02 14:57 UTC, semisse commented on elements/nuxeo-selection/nuxeo-selection-toolbar.js
> +            <span class="count" aria-live="assertive">
Since "assertive" mode will interrupt the user's flow, I would suggest the use of `polite`, since there's no time sensitive or critical action needed.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

2022-11-02 15:19 UTC, semisse requested changes
Please consider my comment.

2022-11-02 16:19 UTC, semisse approved these changes

2022-11-03 04:44 UTC, rakeshkumar1019 approved these changes

2022-11-03 04:51 UTC, swarnadipa-dev approved these changes
Looks good

2022-11-03 05:04 UTC, Nishant0928 approved these changes

2022-11-04 05:34 UTC, rajatgoel-gl approved these changes

2022-11-09 06:38 UTC, merged