WEBUI-935: forbid access to admin tabs if user profile is non admin
nuxeo/nuxeo-web-ui pull request #1643
Opened 2022-11-07 05:30 UTC by swarnadipa-dev

2022-11-07 06:25 UTC, GuruprasadAnk1996 approved these changes, later dismissed

2022-11-07 06:47 UTC, rakeshkumar1019 approved these changes, later dismissed

2022-11-07 06:53 UTC, SnehalNaik-DEV approved these changes, later dismissed
Looks good.

2022-11-09 05:13 UTC, rajatgoel-gl requested changes

2022-11-09 05:13 UTC, rajatgoel-gl commented on elements/routing.js
> +  });
Kindly remove repeatitive code

2022-11-09 05:13 UTC, rajatgoel-gl commented on elements/routing.js
> +  });
Kindly remove repeatitive code

2022-11-10 04:33 UTC, GuruprasadAnk1996 approved these changes

2022-11-10 04:45 UTC, Nisha-QA approved these changes
Looks good

2022-11-10 05:04 UTC, rajatgoel-gl approved these changes

2022-11-10 05:05 UTC, rakeshkumar1019 approved these changes

2022-11-10 05:19 UTC, merged