WEBUI-986: functional test to capture history
nuxeo/nuxeo-web-ui pull request #1673
Opened 2022-11-30 09:12 UTC by Pranit-Sotre

2022-12-07 07:56 UTC, Nisha-QA commented on ftest/features/history.feature
> +    And I can see "Document created" entry in history table
Blank line missing in the end of the file

2022-12-07 07:56 UTC, Nisha-QA commented on ftest/features/history.feature
> +    And I can see "Document created" entry in history table
Validate Download action as well

2022-12-12 05:36 UTC, Pranit-Sotre commented on ftest/features/history.feature
> +    And I can see "Document created" entry in history table
Here download action does not takes place, therefore no need to validate.

2022-12-16 10:42 UTC, Nisha-QA submitted a review, later dismissed
Looks good

2022-12-19 11:47 UTC, rakeshkumar1019 submitted a review, later dismissed

2022-12-19 11:47 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2022-12-20 08:15 UTC, Nisha-QA approved these changes, later dismissed
Looks good

2022-12-20 09:03 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2022-12-21 09:44 UTC, Nisha-QA submitted a review, later dismissed
Looks good

2022-12-21 10:13 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2022-12-26 05:24 UTC, rakeshkumar1019 approved these changes, later dismissed

2022-12-26 06:12 UTC, satishyadav-dev submitted a review, later dismissed

2022-12-27 09:49 UTC, rajatgoel-gl requested changes

2022-12-27 09:49 UTC, rajatgoel-gl commented on packages/nuxeo-web-ui-ftest/features/step_definitions/history.js
> +  this.ui.historyTable.waitForVisible();
Donot use waitForVisible. Kindly use waitForDisplayed for waitForExist

2022-12-27 09:49 UTC, rajatgoel-gl commented on packages/nuxeo-web-ui-ftest/pages/ui/history_table.js
> +    this.el.waitForVisible('#table nuxeo-data-table-row');
Donot use waitForVisible. Kindly use waitForDisplayed for waitForExist

2022-12-27 09:49 UTC, rajatgoel-gl commented on packages/nuxeo-web-ui-ftest/pages/ui/history_table.js
> +    return this.el.$('#table').waitForVisible();
Donot use waitForVisible. Kindly use waitForDisplayed for waitForExist

2022-12-27 09:49 UTC, rajatgoel-gl commented on packages/nuxeo-web-ui-ftest/features/step_definitions/history.js
> +  this.ui.historyTable.isHistoryTableVisible.should.be.true;
Do we really need multiple visible in this functional test case? Kindly re-check and donot use waitForVisible. Kindly use waitForDisplayed for waitForExist

2022-12-27 09:49 UTC, rajatgoel-gl commented on packages/nuxeo-web-ui-ftest/features/step_definitions/history.js
> +  this.ui.historyTable.isHistoryTableFilled.should.be.true;
Do we really need multiple visible in this functional test case? Kindly re-check and donot use waitForVisible. Kindly use waitForDisplayed for waitForExist

2023-01-02 09:17 UTC, Nisha-QA approved these changes

2023-01-02 09:33 UTC, satishyadav-dev approved these changes

2023-01-02 09:44 UTC, rajatgoel-gl approved these changes

2023-01-02 11:28 UTC, Nishant0928 approved these changes

2023-01-02 12:12 UTC, GuruprasadAnk1996 approved these changes

2023-01-02 12:29 UTC, swarnadipa-dev approved these changes

2023-01-04 04:57 UTC, merged