test node v16
nuxeo/nuxeo-web-ui pull request #1684
Opened 2022-12-20 07:55 UTC by rakeshkumar1019

2022-12-26 04:42 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2022-12-26 04:45 UTC, swarnadipa-dev approved these changes, later dismissed

2022-12-26 05:06 UTC, satishyadav-dev commented on packages/nuxeo-web-ui-ftest/pages/login.js
> +  async setusername(username) {
variable  and method name should be in camel case e.g. "setUserName" and "userName". 
correct it for other places as well.

2022-12-26 05:09 UTC, rakeshkumar1019 commented on packages/nuxeo-web-ui-ftest/pages/login.js
> +  async setusername(username) {
Thank you @satishyadav-dev

2022-12-26 09:46 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2022-12-26 09:46 UTC, swarnadipa-dev approved these changes, later dismissed

2022-12-26 09:48 UTC, satishyadav-dev submitted a review, later dismissed

2022-12-26 10:11 UTC, Pranit-Sotre approved these changes, later dismissed

2022-12-27 09:22 UTC, rajatgoel-gl requested changes, later dismissed

2022-12-27 09:22 UTC, rajatgoel-gl commented on packages/nuxeo-web-ui-ftest/pages/login.js
> +    submitBtn.click();
remove multiple times calling of click event.

2022-12-27 09:22 UTC, rajatgoel-gl commented on package.json
> +    "prepare:workbox": "workbox copyLibraries .tmp && mv .tmp/workbox-v3.6.3 .tmp/workbox",
Do we really need to hardcode it?

2022-12-27 09:22 UTC, rajatgoel-gl commented on plugin/web-ui/addon/build.xml
> -      <arg value="--@nuxeo:registry=&quot;https://packages.nuxeo.com/repository/npm-public&quot;" />
Are we sure we dont need it?

2023-01-03 04:17 UTC, rakeshkumar1019 commented on packages/nuxeo-web-ui-ftest/pages/login.js
> +    submitBtn.click();
Done, thank you for comment

2023-01-03 04:19 UTC, rakeshkumar1019 commented on package.json
> +    "prepare:workbox": "workbox copyLibraries .tmp && mv .tmp/workbox-v3.6.3 .tmp/workbox",
here with `v$npm_package_devDependencies_workbox_cli` we are getting error that `workbox-v3.6.3` No such file or directory.

2023-01-03 04:20 UTC, rakeshkumar1019 commented on plugin/web-ui/addon/build.xml
> -      <arg value="--@nuxeo:registry=&quot;https://packages.nuxeo.com/repository/npm-public&quot;" />
yes, its working without this.

2023-01-04 04:21 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2023-01-04 04:27 UTC, Nishant0928 submitted a review, later dismissed

2023-01-04 04:27 UTC, Pranit-Sotre approved these changes, later dismissed

2023-01-04 04:57 UTC, swarnadipa-dev approved these changes, later dismissed

2023-01-04 04:57 UTC, Nisha-QA approved these changes, later dismissed

2023-01-04 04:58 UTC, satishyadav-dev submitted a review, later dismissed

2023-01-04 05:15 UTC, poonamyadav252 submitted a review, later dismissed
Please close PR after the all required approvals

2023-01-13 10:14 UTC, closed without merging