WEBUI-477: fix display of vocabulary listing when loading
nuxeo/nuxeo-web-ui pull request #1694
Opened 2023-01-03 14:04 UTC by poonamyadav252

2023-01-04 09:34 UTC, satishyadav-dev approved these changes

2023-01-04 11:28 UTC, satishyadav-dev submitted a review, later dismissed

2023-01-04 11:55 UTC, Nishant0928 submitted a review, later dismissed

2023-01-04 12:02 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2023-01-04 12:03 UTC, rakeshkumar1019 requested changes

2023-01-04 12:03 UTC, rakeshkumar1019 commented on elements/directory/nuxeo-vocabulary-management.js
> +  _visibleDataTableStyle() {
Since this function is just checking one condition you can use ternary operator to optimize the code.
```
return this.entries.length ? 'display: block;' : 'display: none;';
```
and also since you are using `this.entries` you can remove`entries` parameter from the function  `_visibleDataTableStyle(entries)` .
https://github.com/nuxeo/nuxeo-web-ui/pull/1694/files#diff-0449de7b89ff0a4238b87a5313cf2103b4d1841e6940c8547043d3b6e7a66514R120

2023-01-04 14:15 UTC, poonamyadav252 commented on elements/directory/nuxeo-vocabulary-management.js
> +  _visibleDataTableStyle() {
yes, we are using `this.entries` in the file as a property, but we have to pass `entries` with the function `_visibleDataTableStyle(entries)` to check their length otherwise it will return a `false` value every time.

https://github.com/nuxeo/nuxeo-web-ui/pull/1694/files#diff-0449de7b89ff0a4238b87a5313cf2103b4d1841e6940c8547043d3b6e7a66514R120:~:text=_visibleDataTableStyle(entries)

2023-01-05 05:17 UTC, swarnadipa-dev requested changes

2023-01-05 05:17 UTC, swarnadipa-dev commented on elements/directory/nuxeo-vocabulary-management.js
>            >
No need to pass entries in the function if we are using this.entries inside it.

2023-01-05 05:20 UTC, poonamyadav252 commented on elements/directory/nuxeo-vocabulary-management.js
>            >
@swarnadipa-dev  I replied to the same question that why this is required, kindly find the below link.
https://github.com/nuxeo/nuxeo-web-ui/pull/1694#discussion_r1061525427

2023-01-05 09:10 UTC, satishyadav-dev approved these changes

2023-01-06 06:02 UTC, swarnadipa-dev approved these changes

2023-01-06 06:37 UTC, satishyadav-dev approved these changes

2023-01-06 07:03 UTC, GuruprasadAnk1996 approved these changes

2023-01-06 07:06 UTC, rakeshkumar1019 approved these changes

2023-01-06 07:11 UTC, Pranit-Sotre approved these changes

2023-01-06 09:31 UTC, rajatgoel-gl approved these changes

2023-01-06 09:45 UTC, merged