WEBUI-1034: add functional test for audit page
nuxeo/nuxeo-web-ui pull request #1735
Opened 2023-02-08 13:11 UTC by Pranit-Sotre

2023-02-09 04:22 UTC, rakeshkumar1019 submitted a review, later dismissed

2023-02-09 05:12 UTC, rajatgoel-gl requested changes

2023-02-09 05:12 UTC, rajatgoel-gl commented on packages/nuxeo-web-ui-ftest/pages/ui/admin/audit.js
> +    return this.el.element('#table').waitForDisplayed();
Kindly use $ instead of element

2023-02-09 05:12 UTC, rajatgoel-gl commented on packages/nuxeo-web-ui-ftest/pages/ui/admin/audit.js
> +    this.el.waitForVisible('#table nuxeo-data-table-row');
Kindly use waitForDisplayed

2023-02-09 05:12 UTC, rajatgoel-gl commented on packages/nuxeo-web-ui-ftest/pages/ui/admin/audit.js
> +    return !this.el.elements('#table nuxeo-data-table-row').some((row) => row.getText().trim().length === 0);
Kindly use $ instead of elements

2023-02-09 05:12 UTC, rajatgoel-gl commented on packages/nuxeo-web-ui-ftest/pages/ui/admin/audit.js
> +        const cells = el.elements('#table nuxeo-data-table-cell');
Kindly use $ instead of elements

2023-02-09 05:37 UTC, Nisha-QA commented on packages/nuxeo-web-ui-ftest/pages/ui/admin/audit.js
> +    return this.el.element('#table').waitForDisplayed();
Use $ instead of element

2023-02-09 05:37 UTC, Nisha-QA commented on packages/nuxeo-web-ui-ftest/pages/ui/admin/audit.js
> +        const cells = el.elements('#table nuxeo-data-table-cell');
use $$ instead of elements

2023-02-09 05:37 UTC, Nisha-QA commented on packages/nuxeo-web-ui-ftest/pages/ui/admin/audit.js
> +    return !this.el.elements('#table nuxeo-data-table-row').some((row) => row.getText().trim().length === 0);
Here also

2023-02-09 10:13 UTC, rakeshkumar1019 approved these changes

2023-02-09 10:14 UTC, swarnadipa-dev approved these changes

2023-02-13 08:43 UTC, Nisha-QA approved these changes

2023-02-13 09:47 UTC, rajatgoel-gl approved these changes

2023-02-13 11:02 UTC, merged