WEBUI-1055: fix enuxeo-selectivity displaying entry id
nuxeo/nuxeo-web-ui pull request #1736
Opened 2023-02-13 15:49 UTC by satishyadav-dev

https://jira.nuxeo.com/browse/WEBUI-1055

2023-02-14 04:46 UTC, rajatgoel-gl requested changes

2023-02-14 04:46 UTC, rajatgoel-gl commented on elements/search/default/nuxeo-default-search-form.html
> +            (params.ecm_collections.some((item) => item.displayLabel) ||
Kindly have it more readable and optimized. Also have a false statement as returned.

2023-02-15 10:49 UTC, GuruprasadAnk1996 approved these changes, later dismissed

2023-02-15 10:50 UTC, rakeshkumar1019 submitted a review, later dismissed

2023-02-15 10:51 UTC, swarnadipa-dev submitted a review, later dismissed

2023-02-15 12:34 UTC, Nishant0928 submitted a review, later dismissed

2023-02-16 04:43 UTC, rajatgoel-gl requested changes

2023-02-16 04:43 UTC, rajatgoel-gl commented on elements/search/default/nuxeo-default-search-form.html
> +            (params.ecm_collections.some((item) => item.displayLabel) ||
Kindly optimize it params.ecm_collections.some((item) => {return item.displayLabel || item.title || item.text})

2023-02-16 05:33 UTC, satishyadav-dev commented on elements/search/default/nuxeo-default-search-form.html
> +            (params.ecm_collections.some((item) => item.displayLabel) ||
thank you , optimised it

2023-02-16 07:46 UTC, rajatgoel-gl approved these changes

2023-02-16 08:13 UTC, GuruprasadAnk1996 approved these changes

2023-02-16 08:24 UTC, poonamyadav252 approved these changes

2023-02-16 08:53 UTC, swarnadipa-dev approved these changes

2023-02-17 10:34 UTC, merged