Removing the minor patch upgrade of check engine as yargs version 17 …
nuxeo/nuxeo-web-ui pull request #1761
Opened 2023-03-13 05:20 UTC by swarnadipa-dev

…requires node 12

2023-03-14 08:20 UTC, rakeshkumar1019 approved these changes, later dismissed

2023-03-14 08:34 UTC, Nishant0928 submitted a review, later dismissed

2023-03-14 08:42 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2023-03-14 08:44 UTC, satishyadav-dev submitted a review, later dismissed

2023-03-14 09:58 UTC, rajatgoel-gl requested changes

2023-03-14 09:58 UTC, rajatgoel-gl commented on package.json
> +    "postinstall": "check-engine || true",
No need to change this. Kindly remove it

2023-03-14 10:14 UTC, rajatgoel-gl approved these changes

2023-03-14 10:27 UTC, Nishant0928 approved these changes

2023-03-15 04:13 UTC, GuruprasadAnk1996 approved these changes

2023-03-15 04:18 UTC, merged