WEBUI-831: fix entry/blob update in a nuxeo-data-table
nuxeo/nuxeo-web-ui pull request #1822
Opened 2023-05-02 12:18 UTC by satishyadav-dev

https://jira.nuxeo.com/browse/WEBUI-831

2023-05-04 10:22 UTC, rakeshkumar1019 submitted a review, later dismissed

2023-05-04 10:29 UTC, swarnadipa-dev submitted a review, later dismissed

2023-05-04 15:22 UTC, rajatgoel-gl requested changes

2023-05-04 15:22 UTC, rajatgoel-gl commented on elements/nuxeo-dropzone/nuxeo-dropzone.js
> +      this.files = this.uploadedFiles.filter((item) => item.batchId === value['upload-batch']);
Kindly avoid hard coding

2023-05-04 15:22 UTC, rajatgoel-gl commented on elements/nuxeo-dropzone/nuxeo-dropzone.js
> +      this.uploadedFiles.push(files[0]);
Kindly avoid hard coding 0

2023-05-30 19:12 UTC, satishyadav-dev commented on elements/nuxeo-dropzone/nuxeo-dropzone.js
> +      this.files = this.uploadedFiles.filter((item) => item.batchId === value['upload-batch']);
As discussed with @bchauvin, we can't force client to do configuration changes, better way is to handle it inside our code.

2023-05-31 04:15 UTC, swarnadipa-dev approved these changes

2023-05-31 04:30 UTC, rakeshkumar1019 approved these changes

2023-06-01 05:08 UTC, rajatgoel-gl approved these changes

2023-06-01 08:11 UTC, merged