WEBUI-1171: Fix direct download URL failing with appended clientReaso…
nuxeo/nuxeo-web-ui pull request #1880
Opened 2023-07-04 07:29 UTC by swarnadipa-dev

…n parameter: FORWARD PORT

2023-07-04 09:30 UTC, Nishant0928 submitted a review, later dismissed

2023-07-05 03:32 UTC, rajatgoel-gl requested changes

2023-07-05 03:32 UTC, rajatgoel-gl commented on elements/nuxeo-document-blob/nuxeo-document-blob.js
> +      return this.blob && this.blob.downloadUrl ? this.blob.downloadUrl : this.blob.data;
repetitive code. kindly remove multiple checks of this.blob

2023-07-05 03:32 UTC, rajatgoel-gl commented on elements/nuxeo-document-blob/nuxeo-document-blob.js
> +  _getDocumentBlobUrl() {
use same naming convention '_getBlobDownloadUrl'

2023-07-05 04:41 UTC, swarnadipa-dev commented on elements/nuxeo-document-blob/nuxeo-document-blob.js
> +  _getDocumentBlobUrl() {
done

2023-07-05 04:42 UTC, swarnadipa-dev commented on elements/nuxeo-document-blob/nuxeo-document-blob.js
> +      return this.blob && this.blob.downloadUrl ? this.blob.downloadUrl : this.blob.data;
done

2023-07-05 06:49 UTC, Nishant0928 approved these changes

2023-07-05 06:52 UTC, rakeshkumar1019 approved these changes

2023-07-05 09:17 UTC, rajatgoel-gl approved these changes

2023-07-05 09:44 UTC, merged