WEBUI-1224: expose value-key on nuxeo-document-attachments.
nuxeo/nuxeo-web-ui pull request #1891
Opened 2023-07-26 08:43 UTC by poonamyadav252

2023-07-27 06:46 UTC, swarnadipa-dev approved these changes

2023-07-27 06:49 UTC, rahuljain-dev approved these changes

2023-07-27 09:38 UTC, rajatgoel-gl requested changes

2023-07-27 09:38 UTC, rajatgoel-gl commented on elements/nuxeo-document-attachments/nuxeo-document-attachments.js
> +    const fileName = this.document.type === 'File' && this.xpath === 'files:files' ? 'file' : '';
Kindly avoid Hardcoding 'File' & 'file'

2023-07-27 10:21 UTC, poonamyadav252 commented on elements/nuxeo-document-attachments/nuxeo-document-attachments.js
> +    const fileName = this.document.type === 'File' && this.xpath === 'files:files' ? 'file' : '';
@rajatgoel-gl  It is required that's why i put it here because this is already hardcoded and we have to follow this for now until we will not rewrite all `file:content` related code.

2023-07-28 08:14 UTC, rajatgoel-gl approved these changes

2023-07-28 09:15 UTC, merged