WEBUI-1215: fix enable tab navigation through drawer
nuxeo/nuxeo-web-ui pull request #1910
Opened 2023-08-02 12:11 UTC by swarnadipa-dev

2023-08-03 04:44 UTC, rakeshkumar1019 submitted a review, later dismissed

2023-08-03 04:46 UTC, Nishant0928 approved these changes, later dismissed

2023-08-07 05:13 UTC, rajatgoel-gl requested changes

2023-08-07 05:13 UTC, rajatgoel-gl commented on elements/nuxeo-app.js
> +      this._toggleDrawer(event, { detail: event.target.getAttribute('name') });
Kindly use as below


 this._toggleDrawer(event, { detail: { selected : event.target.getAttribute('name') } });

2023-08-07 05:13 UTC, rajatgoel-gl commented on elements/nuxeo-app.js
> +    }
Simplify this code based on above review comments.

let item = e.type === 'keyup') ? selectedObj : e;

2023-08-07 08:39 UTC, rajatgoel-gl requested changes

2023-08-07 08:39 UTC, rajatgoel-gl commented on elements/nuxeo-app.js
>      }
I dont think this condition is required.. Please check nested if statements are not applicable

2023-08-07 08:58 UTC, swarnadipa-dev commented on elements/nuxeo-app.js
>      }
re wrote the nested if.

2023-08-08 04:13 UTC, Nishant0928 approved these changes, later dismissed

2023-08-09 04:17 UTC, rajatgoel-gl requested changes

2023-08-09 04:17 UTC, rajatgoel-gl commented on elements/nuxeo-app.js
> +      selectedItem.detail.selected &&
I can see there is a repetition of below code

 selectedItem &&
      selectedItem.detail &&
      selectedItem.detail.selected

can we have a local variable for it.

2023-08-09 04:17 UTC, rajatgoel-gl commented on elements/nuxeo-app.js
> +          : selectedItem;
Are we sure this is a valid condition for a specific scenario?

2023-08-09 04:21 UTC, swarnadipa-dev commented on elements/nuxeo-app.js
> +          : selectedItem;
yes, we need this condition to reset the selected item. otherwise, on pressing tab, control moves to the if condition and drawer is closed instead of being open.

2023-08-09 04:35 UTC, swarnadipa-dev commented on elements/nuxeo-app.js
> +      selectedItem.detail.selected &&
done

2023-08-10 08:14 UTC, rajatgoel-gl submitted a review, later dismissed

2023-08-16 03:31 UTC, closed without merging