WEBUI-1066: Fix browser tab name displaying "app.title.undefined" after refresh
nuxeo/nuxeo-web-ui pull request #1925
Opened 2023-08-09 06:19 UTC by rahuljain-dev

https://jira.nuxeo.com/browse/WEBUI-1047

2023-08-10 07:52 UTC, swarnadipa-dev requested changes

2023-08-10 07:52 UTC, swarnadipa-dev commented on elements/nuxeo-app.js
> +    if (!this.page) return;
please write the return statement in the next line for better readability.

2023-08-10 13:20 UTC, rahuljain-dev commented on elements/nuxeo-app.js
> +    if (!this.page) return;
@swarnadipa-dev If we do so prettier will move it to single line, either we can do like this:
if (!this.page) {
      return;
    }
    
    But I don't think it's a good option.

2023-08-11 05:35 UTC, rakeshkumar1019 approved these changes

2023-08-11 05:55 UTC, swarnadipa-dev approved these changes

2023-08-11 09:59 UTC, rajatgoel-gl approved these changes

2023-08-22 06:28 UTC, merged