WEBUI-1260: backward port: need to downgrade chrome browser version
nuxeo/nuxeo-web-ui pull request #1976
Opened 2023-09-19 10:50 UTC by rahuljain-dev

https://jira.nuxeo.com/browse/WEBUI-1260

2023-09-19 11:29 UTC, rakeshkumar1019 approved these changes
Good Job 👍.

2023-09-20 04:21 UTC, poonamyadav252 requested changes

2023-09-20 04:21 UTC, poonamyadav252 commented on plugin/a11y/test/specs/home.js
> +  'color-contrast-enhanced': 2,
This violation should be resolved, Please check if possible to resolve this.

2023-09-20 04:46 UTC, rahuljain-dev commented on plugin/a11y/test/specs/home.js
> +  'color-contrast-enhanced': 2,
This change is done as we move from axe core version from 4.7.2 to 4.8.1.

a11y report with axe-core version 4.7.2:

incomplete: [
[INFO]      [exec] [0-1]     { id: 'aria-allowed-role', issues: 5 },
[INFO]      [exec] [0-1]     { id: 'aria-required-children', issues: 1 },
[INFO]      [exec] [0-1]     { id: 'color-contrast', issues: 2 }
[INFO]      [exec] [0-1]   ],
[INFO]      [exec] [0-1]   violations: [
[INFO]      [exec] [0-1]     { id: 'aria-allowed-attr', issues: 4 },
[INFO]      [exec] [0-1]     { id: 'aria-command-name', issues: 1 },
[INFO]      [exec] [0-1]     { id: 'aria-required-children', issues: 10 },
[INFO]      [exec] [0-1]     { id: 'aria-tooltip-name', issues: 1 },
[INFO]      [exec] [0-1]     { id: 'color-contrast', issues: 12 },
[INFO]      [exec] [0-1]     { id: 'duplicate-id', issues: 28 },
[INFO]      [exec] [0-1]     { id: 'landmark-one-main', issues: 1 },
[INFO]      [exec] [0-1]     { id: 'meta-viewport', issues: 1 },
[INFO]      [exec] [0-1]     { id: 'nested-interactive', issues: 15 },
[INFO]      [exec] [0-1]     { id: 'page-has-heading-one', issues: 1 },
[INFO]      [exec] [0-1]     { id: 'region', issues: 22 }
[INFO]      [exec] [0-1]   ]

a11y report with axe-core version 4.8.1:

[INFO]      [exec] [0-0]     { id: 'aria-allowed-attr', issues: 1 },
[INFO]      [exec] [0-0]     { id: 'aria-allowed-role', issues: 7 },
[INFO]      [exec] [0-0]     { id: 'aria-valid-attr-value', issues: 1 },
[INFO]      [exec] [0-0]     { id: 'color-contrast-enhanced', issues: 2 }
[INFO]      [exec] [0-0]   ],
[INFO]      [exec] [0-0]   violations: [
[INFO]      [exec] [0-0]     { id: 'aria-allowed-attr', issues: 1 },
[INFO]      [exec] [0-0]     { id: 'aria-command-name', issues: 1 },
[INFO]      [exec] [0-0]     { id: 'aria-required-children', issues: 4 },
[INFO]      [exec] [0-0]     { id: 'aria-roles', issues: 3 },
[INFO]      [exec] [0-0]     { id: 'aria-tooltip-name', issues: 1 },
[INFO]      [exec] [0-0]     { id: 'color-contrast-enhanced', issues: 15 },
[INFO]      [exec] [0-0]     { id: 'color-contrast', issues: 1 },
[INFO]      [exec] [0-0]     { id: 'duplicate-id', issues: 28 },
[INFO]      [exec] [0-0]     { id: 'landmark-one-main', issues: 1 },
[INFO]      [exec] [0-0]     { id: 'meta-viewport', issues: 1 },
[INFO]      [exec] [0-0]     { id: 'nested-interactive', issues: 15 },
[INFO]      [exec] [0-0]     { id: 'page-has-heading-one', issues: 1 },
[INFO]      [exec] [0-0]     { id: 'region', issues: 24 }
[INFO]      [exec] [0-0]   ]

This violation changed from color-contrast : 2 to color-contrast-enhanced : 2 as we moved to newer version but not due to any code changes.

2023-09-20 05:26 UTC, rakeshkumar1019 approved these changes

2023-09-20 09:02 UTC, poonamyadav252 approved these changes
Looks good, but only `violation` point needs to be discussed with the PO.

2023-09-20 11:27 UTC, arupmmi07 approved these changes
Reviewed

2023-09-20 12:29 UTC, merged