WEBUI-1385: Fix update of Template properties
nuxeo/nuxeo-web-ui pull request #2171
Opened 2024-02-06 13:33 UTC by alokhyland

2024-02-12 08:05 UTC, swarnadipa-dev submitted a review, later dismissed

2024-02-22 10:20 UTC, madhurkulshrestha-hyland requested changes

2024-02-22 10:20 UTC, madhurkulshrestha-hyland commented on addons/nuxeo-template-rendering/elements/nuxeo-template-rendering-page.js
> +      if (this.unmodifiedDocument === undefined) this.unmodifiedDocument = this._parseJSON(this.document);
Use ternary operator for this condition

2024-02-22 10:20 UTC, madhurkulshrestha-hyland commented on addons/nuxeo-template-rendering/elements/nuxeo-template-rendering-page.js
> +    unmodifiedDocument: Object,
Change name to originalDocument

2024-02-22 10:20 UTC, madhurkulshrestha-hyland commented on addons/nuxeo-template-rendering/elements/nuxeo-template-rendering-page.js
> +    const org = this._parseJSON(this.unmodifiedDocument.properties);
Name should be meaningful. Change this to "orig" or "originalDocument"

2024-02-23 07:12 UTC, alokhyland commented on addons/nuxeo-template-rendering/elements/nuxeo-template-rendering-page.js
> +      if (this.unmodifiedDocument === undefined) this.unmodifiedDocument = this._parseJSON(this.document);
got lint issue

2024-02-23 07:12 UTC, alokhyland commented on addons/nuxeo-template-rendering/elements/nuxeo-template-rendering-page.js
> +    unmodifiedDocument: Object,
done

2024-02-23 07:12 UTC, alokhyland commented on addons/nuxeo-template-rendering/elements/nuxeo-template-rendering-page.js
> +    const org = this._parseJSON(this.unmodifiedDocument.properties);
done

2024-02-23 11:41 UTC, madhurkulshrestha-hyland approved these changes, later dismissed

2024-02-27 06:42 UTC, Nishant0928 submitted a review, later dismissed

2024-02-27 07:34 UTC, swarnadipa-dev commented on addons/nuxeo-template-rendering/elements/nuxeo-template-rendering-page.js
> +  _findChangedValues(object1, object2) {
please change object1, object2 parameter names to something that is understandable in context of the code.

2024-02-27 10:28 UTC, swarnadipa-dev approved these changes

2024-02-27 12:00 UTC, madhurkulshrestha-hyland approved these changes

2024-02-28 06:25 UTC, Nishant0928 approved these changes

2024-03-05 09:36 UTC, merged