Fix web UI 1097 activity tab showing unwanted activity 3.0.x
nuxeo/nuxeo-web-ui pull request #2206
Opened 2024-03-06 07:27 UTC by Nishant0928

2024-03-11 05:45 UTC, madhurkulshrestha-hyland requested changes, later dismissed

2024-03-11 05:45 UTC, madhurkulshrestha-hyland commented on elements/nuxeo-document-activity/nuxeo-document-activity.js
> +    }
what happens is "a" or "a.extended" , "b" or "b.extended" is undefined. Add safe null checks

2024-03-11 05:45 UTC, madhurkulshrestha-hyland commented on elements/nuxeo-document-activity/nuxeo-document-activity.js
> +    }
Use "!a.extended.clientReason" instead of "a.extended.clientReason === undefined"

2024-03-22 05:53 UTC, rakeshkumar1019 approved these changes

2024-03-22 07:52 UTC, swarnadipa-dev approved these changes

2024-03-27 08:29 UTC, madhurkulshrestha-hyland approved these changes

2024-03-27 08:35 UTC, merged