WEBUI-1507-group test case
nuxeo/nuxeo-web-ui pull request #2235
Opened 2024-05-06 11:54 UTC by alokhyland

2024-05-07 10:01 UTC, madhurkulshrestha-hyland requested changes

2024-05-07 10:01 UTC, madhurkulshrestha-hyland commented on packages/nuxeo-web-ui-ftest/pages/ui/group.js
> +      const getElements = await this.el.elements('nuxeo-card[name="groups"] .table [name="id"]');
This is repetitive line which can be taken out of the loop

2024-05-08 05:18 UTC, rakeshkumar1019 approved these changes

2024-05-08 05:18 UTC, alokhyland commented on packages/nuxeo-web-ui-ftest/pages/ui/group.js
> +      const getElements = await this.el.elements('nuxeo-card[name="groups"] .table [name="id"]');
done

2024-05-08 06:37 UTC, madhurkulshrestha-hyland approved these changes

2024-05-08 06:59 UTC, rahuljain-dev approved these changes

2024-05-08 07:24 UTC, merged