WEBUI-1511:BACKPORT- Own Code Static Scan : Open Redirect
nuxeo/nuxeo-web-ui pull request #2246
Opened 2024-05-24 08:35 UTC by alokhyland

2024-05-24 10:58 UTC, madhurkulshrestha-hyland requested changes

2024-05-24 10:58 UTC, madhurkulshrestha-hyland commented on elements/routing.js
> +    const { hostname: currentUrlhost } = new URL(url);
the domains entered by customer can either be
- https://abc.com OR
- abc.com

Add checks in code to handle both type of urls

2024-05-27 07:06 UTC, alokhyland commented on elements/routing.js
> +    const { hostname: currentUrlhost } = new URL(url);
done

2024-05-28 05:15 UTC, swarnadipa-dev approved these changes

2024-05-28 05:50 UTC, rahuljain-dev approved these changes

2024-05-28 08:14 UTC, madhurkulshrestha-hyland approved these changes

2024-05-28 08:20 UTC, merged