WEBUI-1590:Allow option to configure integer display formatting 3.1.x
nuxeo/nuxeo-web-ui pull request #2384
Opened 2024-11-28 17:51 UTC by yashgupta-hyland

https://hyland.atlassian.net/browse/WEBUI-1590

2024-12-02 10:43 UTC, alokhyland approved these changes

2024-12-02 12:04 UTC, rahuljain-dev approved these changes

2024-12-03 06:23 UTC, madhurkulshrestha-hyland requested changes

2024-12-03 06:23 UTC, madhurkulshrestha-hyland commented on elements/nuxeo-results/nuxeo-results.js
> +      Nuxeo && Nuxeo.UI && Nuxeo.UI.config && Nuxeo.UI.config.numberFormattingEnabled !== undefined
no need to check for "!== undefined". remove this part

2024-12-03 10:04 UTC, yashgupta-hyland commented on elements/nuxeo-results/nuxeo-results.js
> +      Nuxeo && Nuxeo.UI && Nuxeo.UI.config && Nuxeo.UI.config.numberFormattingEnabled !== undefined
removed

2024-12-04 05:03 UTC, madhurkulshrestha-hyland approved these changes

2024-12-04 09:28 UTC, merged