Feature lts2021 csp changes part2
nuxeo/nuxeo-web-ui pull request #2396
Opened 2024-12-15 12:53 UTC by alokhyland

2024-12-16 06:11 UTC, madhurkulshrestha-hyland requested changes

2024-12-16 06:11 UTC, madhurkulshrestha-hyland commented on plugin/web-ui/addon/src/main/resources/web/nuxeo.war/ui/index.jsp
> +  if(cspHeader != null && cspHeader.trim().isEmpty()) {
cspHeader == null || cspHeader.trim().isEmpty()

2024-12-16 06:11 UTC, madhurkulshrestha-hyland commented on plugin/web-ui/addon/src/main/resources/web/nuxeo.war/ui/index.jsp
> +    isnewCspHeaderEmpty = true;
isExistingCspHeaderEmpty

2024-12-16 06:11 UTC, madhurkulshrestha-hyland commented on plugin/web-ui/addon/src/main/resources/web/nuxeo.war/ui/index.jsp
> +    String directive = directives[i].trim();
declare directive as String outside the for loop

2024-12-16 08:45 UTC, madhurkulshrestha-hyland approved these changes

2024-12-17 04:59 UTC, rahuljain-dev approved these changes

2024-12-17 05:04 UTC, rakeshkumar1019 approved these changes

2024-12-17 05:05 UTC, merged