NXP-28238: refactor nuxeo-breadcrumb
nuxeo/nuxeo-web-ui pull request #968
Opened 2020-07-14 23:04 UTC by semisse

2020-07-14 23:04 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-28238](https://jira.nuxeo.com/browse/NXP-28238): breadcrumb broken under certain conditions

2020-07-15 10:00 UTC, Gabez0r commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +      ancestors.insertBefore(ellipsis, ancestors.firstChild);
If we are adding the ellipsis before we measure, then we'll display them even if we have just the right amount of space available to display the whole breadcrumb.

2020-07-15 10:02 UTC, Gabez0r commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +      while (ancestors.scrollWidth < ancestors.clientWidth && deletedNodes.length > 0) {
When is this run? I added a breakpoint inside this loop and it was never hit.

I think this happens because we are always reconstructing the breadcrumb, so we are always starting from a position where we just have to remove stuff.

2020-07-15 10:10 UTC, Gabez0r commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +        ancestors.childNodes[1].remove();
We should make sure we handle edge cases here. We should always keep one child element visible, and it can even have a very large title (might require more ellipsis? :scream:).

Can be tested by having a parent folder with a large title. 
![Screenshot from 2020-07-15 11-09-14](https://user-images.githubusercontent.com/13537427/87532882-b48b4000-c68b-11ea-84ae-9c1153fb2c55.png)

2020-07-15 10:11 UTC, Gabez0r commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +        spanTitle.textContent = element.title;
We could add a title attribute as well. It can be useful for long tittles, right? (see last comment)

2020-07-23 10:15 UTC, Gabez0r commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +        this.ancestors.appendChild(listItem);
If `listItem` is large enough, we display the ellispis at the end, but they are truncated. This happens because the `li` elements are overflowing the `#ancestors`. Can't we do something about this overflow?

2020-07-23 16:18 UTC, semisse commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +      this.deletedNodes = [];
I actually think we need to initialize it here to make sure it exists and it is empty, even before the resize.

2020-07-24 09:53 UTC, Gabez0r commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +      this.deletedNodes = [];
But we only use this on `_resize`, right? On resize, we are already checking if it is empty and if so, we do this very same logic.

2020-07-24 16:30 UTC, semisse commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +      this.deletedNodes = [];
we should initialize it here and remove it in the `_resize` method

2020-07-24 16:33 UTC, semisse commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +        this.ancestors.appendChild(listItem);
We want the overflow on the `#ancestors` in order to do the trick. This problema affects a very specific edge case, where we don't have space to introduce the ellipsis generated by the truncation via css text-overflow property. The alternative would be to include yet another method via javascript that would detect the size of the breadcrumb item; detect the size of the generated ellipsis and remove character by character until the ellipsis don't cause text-overflow.

2020-07-29 10:19 UTC, Gabez0r commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +        return this._enrichers.breadcrumb.entries.slice(0, this._enrichers.breadcrumb.entries.length - 1);
nit: could be a one-liner:
```suggestion
      return this._enrichers && this._enrichers.breadcrumb.entries.slice(0, this._enrichers.breadcrumb.entries.length - 1);
```

2020-07-29 10:53 UTC, mnixo commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +            color: var(--nuxeo-link-hover-color, #0066ff);
By setting this fallback, does it mean that we might expect `--nuxeo-link-hover-color` to **not** be defined?

2020-07-29 10:55 UTC, mnixo commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +      return ancestors;
```suggestion
      return this.shadowRoot.getElementById('ancestors');
```
Maybe?

2020-08-05 09:31 UTC, semisse commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +            color: var(--nuxeo-link-hover-color, #0066ff);
Yes, this is a best practice that we should implement every time we use css variables, since it might not be defined

2020-08-14 17:16 UTC, Gabez0r commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +    _getBreadcrumbElements() {
nit: we don't actually get much from having since as a separate method, since this is only called once and it's fairly short.

2020-08-14 17:20 UTC, Gabez0r commented on test/nuxeo-breadcrumb.test.js
> +    await login();
Login already returns a new fake server. I'd expect this to work as well:```
```suggestion
    server = await login();
```

2020-08-14 17:23 UTC, Gabez0r commented on test/nuxeo-breadcrumb.test.js
> +    );
DRY: we have repeated this 8 times on this file. We could wrap in in a helper function.

2020-08-14 17:25 UTC, Gabez0r commented on test/nuxeo-breadcrumb.test.js
> +      expect(separators.length).to.equal(5);
If we are only measure the size of separators, I guess we could just use a counter instead?

2020-08-17 08:43 UTC, nmpcunha commented on test/nuxeo-breadcrumb.test.js
> +    await login();
Indeed, that method is deprecated and you [should use MockClient](https://github.com/nuxeo/nuxeo-elements/blob/master/testing-helpers/test-helpers.js#L144-L147) instead.

2020-08-18 08:45 UTC, Gabez0r commented on elements/nuxeo-browser/nuxeo-breadcrumb.js
> +          value: {},
This is an array, right?
```suggestion
          type: Array,
```

2020-08-18 12:02 UTC, Gabez0r commented
Also, please move this to a WEBUI ticket.

2020-08-19 09:24 UTC, richardsd approved these changes

2020-08-19 09:24 UTC, richardsd commented on test/nuxeo-breadcrumb.test.js
> +      const element = await fixture(
Since this is shared by two test scenarios maybe you can move it to the suite setup as well, wdty?

2020-08-19 09:26 UTC, Gabez0r submitted a review, later dismissed

2020-08-19 09:31 UTC, Gabez0r commented on test/nuxeo-breadcrumb.test.js
> +      const element = await fixture(
But then we'd be initializing it on the other three tests of the suit that do not require it, right? We could also extract this to a function to prevent duplication.

2020-08-19 10:13 UTC, Gabez0r approved these changes

2020-08-19 11:02 UTC, richardsd approved these changes
The new structure makes sense for me 👍 sorry for all the noise 🙂

2020-08-19 11:34 UTC, semisse commented
Not at, @richardsd, it's much better right now. Thank you all for the reviews

2020-08-24 09:58 UTC, Gabez0r requested changes
Please do not push the package-lock.json file.

2020-08-24 17:54 UTC, Gabez0r approved these changes

2020-08-25 08:59 UTC, mnixo approved these changes

2020-08-25 08:59 UTC, merged